### ISSUE TITLE
Reseed DB and Solr

### ISSUE THREAD

**Issue by roastduckalamode** [blakearchive/archive#102]
@nathan-rice 

I'm getting different search results on my local install, mainly just more results. Could you reseed the db and solr on ctools? 

I created a submodule in the repo with the data files I'm using (https://github.com/blakearchive/data). I think those are the right files to use, but I could be wrong.

**Comment by nathan-rice** [comment]
I went ahead and did this, though for the record you should be able to do this yourself -- just modify the config.py file before you run the relevant scripts.

By the way, it looks like you checked config.py into github, that is a definite no-no.  Please do a git remove on it (keep a backup, git remove deletes the file) before your next commit and let me know so I can change the test site database password to something that isn't publically visible.

**Comment by roastduckalamode** [comment]
@nathan-rice 

RE: reseeding. Makes sense. I'll do that from now on. I still have the ctools config backed up and ready. Didn't even think about it. My bad.

RE: checking in config file. Where did you see I checked in the config file? I don't see it in any of the branches. If you are referring to config.py.example, then I see I forgot to fake the secret key. I've faked that now, so you can change as needed.

**Comment by nathan-rice** [comment]
Disregard the config.py issue, that appears to have been an anomaly in my IDE causing the file to be listed as under version control, even though it actually isn't.  My bad.

**Comment by roastduckalamode** [comment]
:+1:
