### ISSUE TITLE
Search Indexing

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#104]
When searching editors' notes, work information should also be searched. I guess it would require indexing the work information in the same field as the editors' notes, or searching on both fields.

**Comment by roastduckalamode** [comment]
I move the first bullet to it's own issue

**Comment by roastduckalamode** [comment]
At 3/23 meeting, it was decided that copy headers (incl. notes) would be separated from object notes.

The final set of indexed pieces are:
### Objects
* title
* img desc
* text trans
* img keywords/characteristics
* Editor notes

### Copy
* copy headers (bibliographic notes)

### Work
* title
* description
