### ISSUE TITLE
Transcriptions in gallery are centered

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#105]
The transcriptions, when shown in the gallery, are centered. They should be subject to the same XSLT as they are in the info boxes. But there seems to be one problem with them in the info boxes: sometimes there are large vertical gaps of space when there shouldn't be

**Comment by roastduckalamode** [comment]
@foxm don't know if this is fixed, but I'll show you where you can edit the tei markup to achieve the styling you want as you come across new errors. As such, I'm going to assign it to you, since you know how it should look.
