### ISSUE TITLE
Clicking on an image in compare should update the bottom half of the object view page

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#107]

**Comment by roastduckalamode** [comment]
@foxm we can hash this out today. To achieve this functionality and keep consistency in the UI, we would need to refresh the page or, at least, update the url. I.e., the page that loads is based on the copy & object parameters in the url. If we didn't update the url, then when a person clicks on a new object, the url would still reflect the old copy/object, and, on a page refresh, would revert to the old object.

Option 1 is to simply update the url as well, which will require some reconfiguring of the route parameters. Not a huge issue, but will take some time.

However, I think we need to take a step back and think about this from the user's perspective. They won't notice these subtle changes in the url and may get confused that they've now jumped from one copy to the next. Here is a user flow as you are suggesting

Homepage > choose work > choose Copy B > select 2 objects to compare (from Copies A & C, they're now in the Compare View) > click on the Copy A object. Now if they return to the Object View or Reading View they will be looking at Copy A. But they entered this interface on copy B. My assumption is that this would confuse a novice user, but it's up for discussion.

**Comment by foxm** [comment]
Not really up for discussion. The UI and user flow design is the result of months of discussion.
