### ISSUE TITLE
Links to the blog and Blake Quarterly need to be added to the bottom banner

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#122]
Blog: The Cynic Sang -- https://blakearchive.wordpress.com/ (this will become subsumed into the archive url space)
_Blake/An Illustrated Quarterly_ -- http://blake.lib.rochester.edu/blakeojs/index.php/blake
_Blake/An Illustrated Quarterly_ Archive (1990-2011) -- http://bq.blakearchive.org/

**Comment by queryluke** [comment]
relates to #150
