### ISSUE TITLE
On large screens the images on the homepage fall short of the right-hand side of the browser leaving empty space

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#123]

**Comment by queryluke** [comment]
I've implemented a fix, but for documentation purposes, this is at the top of override.css
```
@media (min-width: 768px){
    #home.container-fluid.main .row div[class^="col-"] div.scrolling {
        display: block;
    }
    #home.container-fluid.main .row div[class^="col-"] {
        max-width: 300px;
        max-height: 750px;
    }
}

@media (min-width: 1200px){
    #home.container-fluid.main .row div[class^="col-"] {
        max-width: 400px;
        max-height: 850px;
    }
}
```
You can play with the widths of those columns for different screen sizes.

< 768, it will default to 2 columns @ 50% width
>768, but < 1200, each column will have a max width of 300
> 1200, each column will have a max width of 400

You could add more breakpoints and column sizes as you see fit.
