### ISSUE TITLE
In the copy Information, fields and values are misaligned

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#126]

**Comment by queryluke** [comment]
@foxm I'll go digging for an example copy, but if you find one, please post it hear

**Comment by foxm** [comment]
@queryluke @joeafletch 

have a look at the left-hand column of the Copy Information here: http://ctools-dev.its.unc.edu/blake/copy/but244.1

the values don't line up with the fields, but also the values don't correspond to the right fields.
