### ISSUE TITLE
We should discuss italicization of titles

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#130]

**Comment by foxm** [comment]
@queryluke what's the best way to italicize titles all over the site? Like The Marriage of Heaven and Hell. At the data end (the BADs), the import sripts, or the front end? we also need to remove quotations from some of the items like Illustrations to Milton's "Paradise Lost." 'Paradise Lost' should rather be in italics, but 'Illustrations to Milton's' should not be, obviously

**Comment by queryluke** [comment]
@foxm It depends on how universal the application is. If every work title should be italicized, then that would happen on the front end. But it sounds like this varies by work title. E.g.

1. _The Marriage of Heaven and Hell_ (all italics)
2. Illustrations to Milton's _Paradise Lost_ (partial)

Thus, I'm inclined to say this should happen on the data end. But this means html in the title strings. What are your thoughts, @nathan-rice?

**Comment by foxm** [comment]
I'm thinking now maybe we should only italicize non-Blake works like Paradise Lost in the titles. I'll talk to the editors about it.

**Comment by nathan-rice** [comment]
If we need partial italicization of titles, that is going to have to be introduced at the data level.  Likewise, if you want to remove quotes, the correct place to do that is by modifying the source data.  If you don't want to modify the bads, I could populate the title field via a CSV file with a column for HTML title data - I think updating the bads is cleaner though.

**Comment by queryluke** [comment]
relates to #295 

As it stands now, anything that is run through the xslt, should continue to use <hi rend="i">. This includes:
* textual transcriptions
* electronic information
* illustration descriptions

Other information in the BADs should use markdown to style the text. There is a markdown filter available:
```
<span ng-bind-html="stringtobind | markdown">
```
Where `stringtobind` is the text you want to run through the markdown filter

**Comment by foxm** [comment]
@queryluke wait, i thought you'd said use *. One of our assistants is busy editing the BADs using *'s.

**Comment by queryluke** [comment]
@foxm Sorry for the confusion. #295 indicated you SHOULD update illustration descriptions (and copy header/source) but not electronic information or textual transcriptions. I've updated my comment above to reflect this. (Before I had illustration descriptions as something you shouldn't edit)

**Comment by foxm** [comment]
@queryluke thanks, luke, but my question was about the format of the markdown. you'd mentioned using *'s, not `<span ng-bind-html="stringtobind | markdown">`, as in *stringtobind*

**Comment by nathan-rice** [comment]
The * is inside the string.  The <span ...> is how you have to reference the strings inside angular templates.

**Comment by foxm** [comment]
ah, ok, so continue to use just *'s in the BADs?

**Comment by nathan-rice** [comment]
Correct, * in the bads.

**Comment by queryluke** [comment]
Correct. The above was just an example for future reference. I.e., how you would render markdown from a BAD within the angular app
