### ISSUE TITLE
Implement Erdman

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#133]
Erdman needs its own place in the database and another solr core/schema for searching it:

http://www.blakearchive.org/blake/erdman.html

**Comment by foxm** [comment]
It can be displayed as the static pages are displayed with a sidebar menu for chapters and sections

**Comment by foxm** [comment]
@joefletch i'm attaching the erdman xml files here

[erdman.zip](https://github.com/blakearchive/archive/files/205183/erdman.zip)

**Comment by queryluke** [comment]
@nathan-rice looks like the zip file is [this directory](https://github.com/blakearchive/data/tree/master/erdman) in the data repo

**Comment by nathan-rice** [comment]
Erdman probably does not need to be represented in the database.  I expect that it will be consumed as a monolithic unit, so breaking it down to a relational model is just going to introduce needless complexity.

It may or may not need to be represented in Solr - that buys us stem word matching and a few other minor perks, but a javascript search solution using regular expressions should be adequately performant given the size of the data set, quite powerful, and much simpler.

**Comment by foxm** [comment]
i agree--javascript for this is simpler and adequate. we don't want to paginate the display, though, because the ability to use ctrl-f in a given section is very handy

**Comment by queryluke** [comment]
Here is the list of top user stories/desired functionality for the Erdman, as discussed by editors and staff at Blake Camp. Let me know if you have any questions.

1. search key words and phrases written by Blake, and their corresponding Erdman page number
2. see the entire sentence or page or work that the searched for word is coming from
3. search for page numbers of quotations, used for checking quotations in essays
4. cut and paste text to use in one’s essays
5. concordance light: to see how often and where Blake used a term; this use may require a display different than the one we are imagining with Google books search display; this might need a list of sentences, what I mean by concordance light. We get that effect with our current Erdman interface within a work, once you turn the triangle to get the nested results to display; but you need to do that for all the works in the hit list
6. to be able to read a whole page or section, like Public Address, online
7. access Erdman’s textual notes​

**Comment by nathan-rice** [comment]
It seems to me that the only thing motivating a retention of the existing book structure is the fact that you need page numbers for reference purposes.  In terms of how you actually use the site, the book structure is incidental.

Looking at your use cases, data model that includes sections, works, sentences, lines (for rendering/bibliography purposes), pages (ditto) and commentary (so Blake's writing is searchable separately from Erdman/etc's).  This is all fine, the big problem I see is that the actual text contents exist in an XML structure that isn't amenable to being broken down and reformed using this schema.  As a result, we'll probably need to have the application and search data model diverge, much as with the virtual copies issue.

**Comment by foxm** [comment]
i just had a long discussion with joe f. and joe v. about erdman. it occurred to me that we don't need to index erdman in solr. if that's already been done, though, then i guess the rest of this comment is moot.

if not, i just want to put the following on the table. we don't need all the benefits of a search engine index like relevance ranking, logical operators, or multi-word searches. what joe v. wants is a concordance and a way to look up words in the concordance. so all we really need to do is write one script to generate the concordance one time, put it in one big file (or database table), and provide a way to lookup a word in it. a lookup of a word would return the entry consisting of all the lines that contain that word.

here's an example of a biblical concordance:

https://books.google.com/books?id=o22QQyRnqbIC&printsec=frontcover&dq=biblical+concordance&hl=en&sa=X&ved=0ahUKEwj9_azlzsvOAhWCHx4KHXUjDwIQ6wEISDAI#v=onepage&q&f=false

the format for erdman would be similar:

Word
Work A, Date, Erdman page number, text of the line in which the word occurs
Work B, Date, Erdman page number, text of the line in which the word occurs

the concordance file could be sorted by word, work, or date. a user could do a lookup by word, work, or date range, or any combination of those.

**Comment by queryluke** [comment]
has it's own repo: https://github.com/blakearchive/erdman
