### ISSUE TITLE
Reading View should not contain the bottom half of the page nor the button tools

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#136]

**Comment by foxm** [comment]
I implemented this in branch reading-view-changes, and it works, but you might want to check on it. The logic I put in place seems backwards to me. I think I'm missing something about Angular.

**Comment by queryluke** [comment]
@foxm 

What you did is correct in terms of logical workflow of angular. But you did more than you needed to. Where you added ```ng-if="copyCtrl.$storage.view.mode != 'read'"``` **line 32, copy.html)** is sufficient. You didn't need the additional functional overhead. 

If you wanted a button somewhere that actually toggled the bottom half of the page, then yes, you would need this function, and the way you've approached it is correct.

**Comment by foxm** [comment]
@queryluke thanks, luke. so the ng-if is not predicated on the truth value of hideArchiveTabs which is initially set to true? it just means, show the div if ng-if is true? hideArchiveTabs would just be for the toggle function used with a button?

**Comment by queryluke** [comment]
exactly, ng-if will render the element (and all its children elements) based on if the expression is true, in this case ```copy.Ctrl.$storage.view.mode != 'read'```.

There is also ng-hide/ng-show, which is similar but accomplishes a hide/show using css (display:none). In generally, you use ng-hide/ng-show if you want the element to appear with a transition or animation. So, if we wanted a button to toggle the tabs section, we'd used ng-hide/ng-show instead and use the toggle function you wrote.
