### ISSUE TITLE
In reading view, single clicking object or label (Object 1 (Bentley 1, Erdman 1, Keynes 1) should take you to the object view for that object

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#137]

**Comment by queryluke** [comment]
@foxm we've already got dblclick taking them to object view. Additionally, we should think about how user's with a standard mouse (only y-axis scrolling) will navigate this view. They would need to click and drag the scrollbar at the bottom of the viewer. Another option would be to make a single-click + drag move through the pages.

**Comment by foxm** [comment]
@queryluke oh, i thought i'd noticed that the double clicking wasn't working in the reading view. yes, the scrollbar should be there. and i guess we could make that single-click and drag an additional option, but it's not necessary

**Comment by queryluke** [comment]
@foxm re:click and drag - good to know. I'll make it a low priority. Re: dblclick, I implemented it this afternoon, so it may not be on ctools. But the latest version of Master branch has it.
