### ISSUE TITLE
when initially opened the top half of the object view page is too short; the tabs should just barely show at the bottom of the browser window

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#142]

**Comment by queryluke** [comment]
@foxm I just made things a bit larger. But you can adjust to what you see fit. You need to adjust the values in 5 places. I'd like to eventually clean this up a bit, but the way devhammer has the elements structured makes things a bit difficult at the moment.

The first 4 use the objectWindow directive, which really just sets the height of the element based on the **adjust** value you pass:

/controllers/copy/copy.html
line 4

/directives/object-reading/objectReading.html
line 7

/directives/object-viewer/objectViewer.html
line 8

/directives/object-compare/objectCompare.html
line 15

(this one does it's own calculations, again, something that should be cleaned up at some point)
/directives/info-tray/infoTray.directive.js
line 7


You'll notice that copy & info tray need the same value, viewer and reading need a value that's ~ 120px larger (but you can play with the different), and compare needs a value that is 5 less than viewer/compare
