### ISSUE TITLE
implement zoom

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#144]
We should get rid of the zoom button and just make it so that when the user hovers over the image, a magnifying glass shows up and the respective area gets magnified.

I've been trying to implement this with bootstrap-magnify (https://github.com/marcaube/bootstrap-magnify), but I've had no luck so far.

**Comment by foxm** [comment]
@queryluke the manual way doesn't seem to work either, unfortunately

**Comment by queryluke** [comment]
@foxm yeah, looks like that plugin isn't compatible with angular. I managed to find and angularized version but it will need some retooling to work with our setup.

https://github.com/jotielim/ng-magnify

**Comment by queryluke** [comment]
@foxm

I think I've managed to implement this on the zoom-trial branch. Please take a look and let me know if you come across any bugs

**Comment by foxm** [comment]
@queryluke very nice, luke!
