### ISSUE TITLE
rotate needs to resize object view window for images that are wider than they are high

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#145]
For example: http://localhost:8002/blake/copy/biblicaltemperas

**Comment by foxm** [comment]
@queryluke i moved the obj.transform.style from the img to the container div so that the image doesn't get cut off by the div when it rotates. i had done this in a previous commit. not sure how it got lost.

**Comment by foxm** [comment]
@queryluke hey luke, i'm re-opening this because it's still not resolved. was my comment misleading? have a look at the example. rotating images that are wider than they are high causes them to get cut off by the gallery window

**Comment by queryluke** [comment]
Are you looking at ctools? Or the latest master branch. You may need to do a git pull locally to get the latest version of master

**Comment by foxm** [comment]
yeah, i did that right before i wrote my last comment. don't know why i didn't pick up the change

**Comment by foxm** [comment]
just tried again. still no change

**Comment by foxm** [comment]
i see the changes to the ovpImage directive, but the whole gallery window needs to stretch when the image turns 90 degrees, not just the div img container. and the image manipulation tools should go down and the tabs should go down to allow the whole image to be visible as it turns 90 degrees. and then as it turns 180 degrees, the gallery window should contract to its original height, and the tools and tabs should move back up

**Comment by foxm** [comment]
just noticed, too, that the other images, the ones whose width is less than their height, get cut off now by the div container when they're rotated 90 degrees

**Comment by queryluke** [comment]
@foxm 

this is mostly fixed. The rotate button in the compare view rotates all the objects. I figured out a way to rotate only a single object, but caused more problems than it solved.

I can't foresee allowing single object rotation in the compare view without completely refactoring devhammer's setup and most of the gallery scripts. Thus the two options moving forward are to allow the multiple object rotate (how it is now), or remove the toolbar in the compare view. If the latter, the compare view workflow could be reworked slightly. I.e., instead of dblclicking to go to the gallery view, a single click would go to the gallery view. Then add a button, "Back to compare", so users can quickly return to the compare view with their selected objects.

**Comment by foxm** [comment]
@queryluke very nice, luke, thanks. left you a comment in the commit. 

i like how they all rotate at once in the compare view. let's leave it as is. would it be possible, though, to reset the rotation as you go to the next or previous object in the object view? right now, the next or previous object come up rotated

**Comment by queryluke** [comment]
@foxm whoops! yes very doable. I had it that way but had to restructure some things when I we messing around with the single object in compare view. I'll have that fixed in a minute. I'm working on the compare for sequence an motif so i'll wrap those in the same edit

**Comment by foxm** [comment]
@queryluke great job, man. and thanks, i'm looking forward to showing that compare feature to the editors. they're not able to imagine these enhancements sometimes. they have to be shown. if possible, could you include the medium in the labels below the images in the compare feature for sequence and motif? that'll make it clear to the user that they're not looking at 'copies' but others types of relations in the compare view

**Comment by queryluke** [comment]
@foxm where would I find the medium info, is it on each individual object, or on their work?

**Comment by foxm** [comment]
@queryluke Object.selectedObject.source.objinfo.medium.text
<https://contactmonkey.com/api/v1/tracker?cm_session=f1d99e1b-9b55-4063-a84a-c46412cc4629&cm_type=link&cm_link=ac44aad4-b2ba-49e9-a914-b6d803b1a197&cm_destination=http://Object.selectedObject.source.objinfo.medium.text>

but sometimes these are long strings. it might be best to just say "From
[menu category]." for example, "From Manuscripts and Typographic Works" or
"From Drawings and Paintings."

the medium might be easier to grab, i realize.

but on second thought, don't worry about providing the medium because when
the user single clicks on the object, all of that info, including the
medium, shows up below!
