### ISSUE TITLE
Object meta data tab

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#158]
should show embedded textual data in the image. I've written scripts that cull information from various files and embed it in the image

on the current site, this gets accessed from the lightbox (java applet)

**Comment by queryluke** [comment]
@nathan-rice has this been discussed before. I don't see this information in the python import scripts.

**Comment by nathan-rice** [comment]
Image metadata was mentioned in a previous meeting, though no decision regarding its storage or use were reached. If that data has been embedded in the image (I'm assuming via EXIF tags, though none of the JPEGs I downloaded from the site had any), it wouldn't be pulled in through the current import script, which only processes bad xml documents.

I could certainly amend the import script and data model to include this additional metadata if I knew the source location.  The other alternative is we can pull the data on the site from the images, using javascript.  The best course of action really depends on how the metadata is going to be used.

**Comment by foxm** [comment]
the metadata shjould only be embedded in the 300dpi images that you can access via the Lightbox or Show Enlargement. i'll have to look back at the scripts i use for this. i wrote them a long time ago and they're part of a larger script for our publication workflow

**Comment by foxm** [comment]
Let's take out the metadata display from the infobox and leave it for the Lightbox
