### ISSUE TITLE
Letters: Virtual Groups with Multi-Object Constituents

### ISSUE THREAD

**Issue by joeafletch** [blakearchive/archive#161]
@nathan-rice 

Just starting this thread here. You can see how we display letters on the current site [here](http://www.blakearchive.org/exist/blake/archive/vgroup.xq?id=letters&java=no&titles=&landing=object&mode=vcopy), but we need to approximate this display using the grid of handprints that we are using in the redesign to display copies and objects. All this without breaking the current work-->copy-->object schema. Currently on ctools, only the first page/object (usually the "address" page) of each letter is being displayed, and subsequent objects are inaccessible. 

Mike and I discussed this and wonder if we can treat each multi-object letter as a virtual "copy," so that the first object/handprint gets displayed on the grid for the letters work page. These "copies" will be labeled according to the title of the letter (taken from the BAD) and not labeled as objects (as they currently are on ctools). From there, users choose whatever "copy" (first-object handprint) they want and are taken to the OVP for object 1 of that "copy"; they can then click through the four (or however many) objects in that "copy", which are also displayed in a grid beneath the "Objects in Letter [we'll have to change the label of this tab with Luke]" tab.

How does that sound?

**Comment by nathan-rice** [comment]
The virtual copy concept is definitely doable.  This would give you good search granularity and matches the structure of the data fairly well.  The downside is that if you wanted to quickly explore objects with a matching motif for various members of the virtual work, or compare images in separate virtual copies, those become quite tedious.

Another option is to annotate the model for objects to include an "object group" field.  Objects in the same object group could be collapsed by default in the interface, and expanded using a similar mechanism to the one we're conceptualizing for search results.  This object group feature could also be used to group objects with conceptual relationships in non-virtual work objects as well.  The downside is that any bad that is part of a virtual work group will be excluded from copy searches since virtual-work copies discard the source and header data from the original bads.  The copy information tab will also be absent for virtual work copies.

I'm not completely happy with either option, so I will continue to consider the possibilities.

**Comment by nathan-rice** [comment]
One possibility that occurs to me is to diverge the postgres and solr models for these multi-object virtual work copies.  On the postgres side, we could add the object group field, and update the copy interface to support object groups inside the copy.  On the solr side, we could use the concept of the virtual copy for search purposes, so you could locate them via headers/source.  It is a little bit more work (and diverging your data model this way usually isn't the best choice) but it gets us the best of both worlds without a major data model upheaval.

Are all the "virtual copies" represented by individual bads currently?  If so, I'll just need a CSV document with the following information:

* the bad_ids of documents that should be treated as virtual copies
* the name of the "object group", if different from the bad's title.

**Comment by joeafletch** [comment]
@nathan-rice I know this is in the process of being worked on, but I wanted to add one thing to what I wrote above: once a user is clicking through OVPs of a particular letter, there should also be the option to click through (or back) to the next (or previous) letter in the chronological sequence. Thus, it would be ideal to have--in the case of virtual groups with multi-object members like this--a "Next Letter" and "Previous Letter" option on the OVP, in addition to the "Next Object"/"Previous Object" buttons (the former could be above the latter). 

Also, another tab containing a grid of all the letters in the group (in addition to the tab containing a grid of all objects in a particular "copy" (letter in this case)) would be helpful on each OVP in these cases.

**Comment by nathan-rice** [comment]
If the objects in a copy of a virtual work are grouped by "object groups" and sorted by composition date, it will be fairly straightforward to add "next object group"/"previous object group" buttons to the OVP object-viewer, which should satisfy your desire to be able to page to the previous/next letter.

As for adding an additional tab for all the objects in an object group, I think this will be better achieved using a "fly-out" menu, of the same sort we end up using for the search page.  There are several reasons for this:

* Not all objects in a virtual work copy will necessarily be part of an object group, and having the tab appear and disappear is bad UI design.
* You might be scrolled down below where the tabs are visible, but want to see all the objects available in the object group - having a flyout menu makes this easy, whereas with tabs you'd have to scroll back up to the tabs menu.
* If you want to see objects in several object groups at once, or want to quickly switch between object groups, using tabs makes this tedious, but with a flyout menu it is easy.

**Comment by foxm** [comment]
even though we now have the overlay that allows quick access to other letters from the object view, we still want a way to navigate to the next and previous letter from within the gallery window. i think the icons for next and previous letter should go in the top left and top right corners. this way someone can read through the letters chronologically very easily

**Comment by queryluke** [comment]
making a new issue for this
