### ISSUE TITLE
put the WBA banner at the top of the stand-alone windows like the enlargement window

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#164]
http://ctools-dev.its.unc.edu/blake/new-window/enlargement/but244.1?objectId=1456

**Comment by queryluke** [comment]
@foxm 

do you want the entire header (and/or footer)? Meaning all the navigation functions as well?

Or just the very top banner with the signature (i.e., no search box, lightbox button, or menu button)

**Comment by foxm** [comment]
@queryluke woops, meant to be specific. just the very top banner with the signature (no other buttons or boxes)
