### ISSUE TITLE
add icon for generate citation

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#170]

**Comment by queryluke** [comment]
@foxm Once you find an icon, you can assign this to me. If you want to use an icon devhammer has already provided, they are found in blakearchive/static/img/global

**Comment by foxm** [comment]
@queryluke here's a good one: https://www.iconfinder.com/icons/175680/quote_icon#size=26

if you could, make sure it's filled with the same shading of black as the other icons. i figure you can use an eyedrop tool
