### ISSUE TITLE
title and 'copy x' sometimes run together in compare view -- might be a problem on the data end

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#172]
for example, copy b of songs of innocence and of experience in a compare window

**Comment by queryluke** [comment]
@foxm @joeafletch Where should the copy title come from. @nathan-rice resolved the Work and Object titles #100, but we need to resolve the copy titles. Right now, the copy titles are including the "Electronic edition" string.

**Comment by joeafletch** [comment]
@foxm @queryluke This is tough. That "electronic edition" is included in all BADs, and as Mike stated, it seems redundant and silly. We could perhaps run a script to remove these from all the BADs (have to check with the editors), unless there's another way for the code to ignore it. It doesn't actually appear between the <copy> tags (It always looks like this: "<copy>copy G</copy> : electronic edition </title>"). I suppose you could get the copy designation from the BAD element (top line), but up there "Copy" doesn't appear--just "copy='G'" etc.

**Comment by nathan-rice** [comment]
It would be pretty easy to just to take copy title text up to the colon.

**Comment by nathan-rice** [comment]
Done.
