### ISSUE TITLE
add compare buttons for Objects for Same Motif and Objects from Same Production Sequence

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#176]
@joeafletch hey joe, wouldn't this be good? joe v. always says compare is only for 'same matrix' and any other objects can be compared in the lightbox, but why not make all the editorially defined relations comparable and then leave everything else to the lightbox

**Comment by foxm** [comment]
@queryluke would it be possible to put this in place in a quick and dirty way so that we can show the editors? i see there's a separate directive for objectsfromthesamematrix

**Comment by foxm** [comment]
@queryluke looks great, luke. just one thing, though. when you've selected an image in the compare view and you hit another tab, the objects being compared shouldn't go away. right now, they disappear and leave the selected object by itself (and all the way to the left of the gallery window).

**Comment by queryluke** [comment]
@foxm I made compare restricted by type. And it was reseting on the tab change. Now it's more graceful: it won't reset the compare view unless you choose an object of a different compare type. E.g., you're comparing objects of same matrix, then choose an object of same sequence, then it will reset.

But if you want an open compare, meaning someone could compare all objects across the same matrix, motif, and sequence, let me know.

**Comment by foxm** [comment]
@queryluke perfect, that's how it should be. we don't want to allow comparisons across types
