### ISSUE TITLE
rotate in compare

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#181]
@queryluke luke, when the objects rotate in compare they overlap. they should spread out so they don't overlap, but their titles of course should stay centered above them. hope this is an easy fix for you

**Comment by foxm** [comment]
@queryluke nice. you just gotta make it so that when you rotate 180, the divs should contract back to their original width

**Comment by queryluke** [comment]
@foxm They are contracting back for me. What browser are you using?

**Comment by foxm** [comment]
@queryluke latest chrome

**Comment by queryluke** [comment]
@foxm I was noticing some other bugginess that I just flushed out. let me know if it fixes it for you

**Comment by foxm** [comment]
works! very nice, man
