### ISSUE TITLE
put titles above gallery window (in the center of the banner); white text against black background

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#182]
the black background should look like browser tabs look, angled in and sitting on the edge of the window

**Comment by foxm** [comment]
@queryluke i added a directive for this in the branch worktitle, but i couldn't get it to access the data model for some reason. when you get a chance, can you have a look at this? the directive is workTitle

**Comment by queryluke** [comment]
When you instantiate the workTitle directive, you need to pass a copy and/or work.
```
<work-title copy="copyObject" work="workObject"></work-title>
```

Note in workTitle.directive.js, line 36 & 37 correspond to **copyObject** and **workObject** above. You need to pass the data models to the directive. Then the models will be available in the contorller as **vm.copy** and **vm.work**, or in the template file as **workTitle.copy** and **workTitle.work**

**Comment by foxm** [comment]
@queryluke i see, i think that's what the problem is. i'm using work-title in main.html, which doesn't have access to a copy or work

**Comment by queryluke** [comment]
ah, then this is a larger issue with the BlakeDataService workflow. As briefly as possible:

The workflow of passing objects from controller to directives (as I said to do above) is not ideal. However, when I first started on the project, the changes in the BlakeDataService (e.g. when you select a new object) weren't registering with all the directives. Additionally, the directives and controllers were creating new instances of the BDS., causing mismatched data. At that point in time, the code base was fairly limited and it made sense to keep the scope attached to the controller.

But now, this method is causing too many problems. I was hoping we could get to a production release before having to refactor, but it looks like I need to address this now.

**Comment by foxm** [comment]
sounds good, luke

**Comment by Grantglass** [comment]
Mike, I messed around with Dream Weaver last night to see if I could get it to work, no luck for now, but I can continue to try. However, it sounds like a larger issue related to the workflow. Let me know if you want me to continue to attempt this through Dream Weaver

**Comment by queryluke** [comment]
@foxm 

I've refactored how data gets passed around. In any controllers, if you include *BlakeDataService* then attached it to the vm object, you'll have access to all the data. You can see a brief outline in my comment on #236 

You can take a look at the changes I made to your work-title directive.

**Comment by foxm** [comment]
@queryluke thanks. i'm almost there. at the moment when i move between object view and work info, there is a temporary transitionary state in which the title box in the banner shows the work title of the copy from which i came. it flashes before the actual work title shows. i'm using $rootScope.onWorkPage to determine what to go in the title box, either the work title or the copy title, depending on whether the user is on the work info page or the object view page. anyway, i'll keep hacking away at it. i'm sure there's a better way for me to do this

**Comment by queryluke** [comment]
@foxm looks fine to me. That little bit of lag between views can be cleaned up when we start optimizing. I've noticed lag in other areas, so I wouldn't worry about it too much. Something I can hash out later.

You will need to adjust the info tray height once you get everything settled. *info-tray/infoTray.directive.js: line 25*

```
var adjust = angular.isDefined(adjust) ? 131 - adjust : 131;
```

Messing with the *131*'s will align the info tray button.

**Comment by foxm** [comment]
@queryluke I got ya. If you notice, though, the string actually changes briefly, which leads me to think it is getting set twice. In other words, it's not just carrying the value on the ovp to the work info page. Will adjust that height, thanks

**Comment by foxm** [comment]
two problems introduced in this branch now:

1. i made the compare page show the work title plus "(Selected)" in the banner to indicate which copy is selected. but now it seems when you double click to go back to the object view, you can't then select a work from the menu. you have to select one (and have nothing happen), then select another to get that one. very strange.

2. when you show a compare view for a work, then navigate away to another work and show a compare view for that work, you end up retaining one object from the original work in that new compare view. again, very strange.

**Comment by queryluke** [comment]
@foxm I think these are issues with the backend refactor. making a new bug issue for it
