### ISSUE TITLE
Copyright icon should appear at the end of the image label on the OVP

### ISSUE THREAD

**Issue by joeafletch** [blakearchive/archive#191]
This should generate a pop-up window containing the textual information found in the <userestrict> tags of all BADs.

**Comment by foxm** [comment]
@queryluke i started to implement this and #193 and #192. but there are still a few things to fix: 'Object X' needs to be centered and the spacing needs to be adjusted to allow the label under the image without having to scroll. also, the copyright link leads to the Color Key modal right now, just as a placeholder. i couldn't figure out how to create an html file in the modal directory that can access the Use Restriction for each object (header.userestrict)
