### ISSUE TITLE
Supplemental Views/Inscriptions

### ISSUE THREAD

**Issue by joeafletch** [blakearchive/archive#198]
@nathan-rice @queryluke 
We've put off this bit of functionality, but as we get toward the end of functionality issues, we should address it:

Several objects have what we call "supplemental views," which either means that we have a full-page image of the object in, say, an illuminated book (most images as they appear on the OVP are cropped), or we have an image (or several images) of inscriptions that appear either on the same side of the page as the OVP image, or on the backside (verso) of the page. On the current site, in order for these images (which have their own dbi) to display, we had to develop separate BADs for them, such as "suppvda.h" or "relamerica.b", which were unique only insofar as they pointed to those unique images (the copyheader and other info in the BAD was just copied from, say, vda.h or america.b). Thus, long ago, I told Nathan to ignore all BADs  that began with "rel" or "supp"--since we don't want to treat those images as separate copies.

But right now the images for those supplemental views and inscriptions are being included in the "Objects from the Same Production Sequence" tab, which is due to their placement in the relational data spreadsheet. So we will need to adjust that on our end, presumably by creating a new column for "Supplemental Views/Inscriptions." But in terms of how to access these images on the new site, we propose adding a Supplemental Views/Inscriptions button (only when pertinent of course) to the row of tools containing Zoom, True Size, etc. (as opposed to adding a new tab below this row). Clicking on this button will replace the OVP image with either the supplemental view/inscription image--if there is only one--or a grid of handprints of supplemental views/inscription images if there are more than one. Once that Supplemental Views/Inscriptions button is clicked, it will change to read "Normal View" in order for the user to revert back to the original OVP image.

We can discuss this further at tomorrow's meeting.

**Comment by joeafletch** [comment]
@queryluke @nathan-rice 
This is more complicated than I had originally thought/explained. It turns out that the supplemental inscription images, etc. ARE marked up/transcribed, so we can't just dispense with the BADs (like relamerica.b and inscbut.439, etc.), since they contain info that's not in the BAD for the original object. So the solution we came up with at today's meeting--adding a "supplemental" tag to the original BAD and then pointing to the pertinent dbi(s) for all such objects--isn't going to work, since we want information beyond just the image. That info IS currently showing up on the redesigned site once those inscriptions/supplemental views are clicked on; the trick is just to treat those cases differently--so the supplemental/inscription images aren't included in the "Objects from the Same Production Sequence" tab and so they aren't treated as a separate copy, but instead have their own icon on the OVPs of the regular objects with which they're associated.

Mike thinks the best solution would be to modify the relational data document. Would it work just to create a new "Supplemental views/inscriptions" column and move all the pertinent desc ids into it (and out of the "related ids" column, where they all currently are)? (The dbis associated with those desc ids are indicated elsewhere in the relational table.)

**Comment by joeafletch** [comment]
@queryluke Having trouble remembering the conclusion of the discussion that you, Mike Fox, and I had about this a couple weeks ago. Mike thinks that ultimately you convinced us that the BADs needed to be modified to include a tag that pointed to the supplemental/inscription images/objects. Could you reiterate the reasoning you gave us for why that would be the better option--as opposed to modifying the relational table by adding a column for inscriptions/supplemental images?

**Comment by nathan-rice** [comment]
As much as possible, you want a single source of truth, which should be the original data.  CSV documents with ancillary data should be used for things that are only germane to the blake archive web site.  These extra images (with transcriptions and notes) seem relevant outside the context of the site.

Additionally, these supplemental documents aren't "blake documents" in the strictest sense, so you are bastardizing your data model by treating them as such.  Such bastardizations typically require "special case" code to handle, and that code will have to be maintained (along with documentation) for the entire life of the archive.

**Comment by joeafletch** [comment]
True, the inscriptions are often not "blake documents" in the strictest sense (though the supplemental views are supplemental views of "blake documents"), which is why the editors--after lengthy discussion--opted to treat them separately. 

Sounds like you're suggesting we update the BADs rather than modify the relational CSV document. If that makes more sense from a coding standpoint, no problem.

**Comment by joeafletch** [comment]
@nathan-rice @queryluke Okay guys, I've modified all the pertinent BADs to include the information for the inscriptions and supplemental views. This information--pulled from those BADs beginning with "insc", "supp", and "rel", are now all contained in a <supplemental> tag for each pertinent object in the original BAD. Let me know if you have any questions or if you come across any problems.

**Comment by queryluke** [comment]
As discussed in 7/13 meeting:

Need to add a "supp" attribute to the blake-object model. When finished, I'll start on the ui.

**Comment by nathan-rice** [comment]
This has been implemented.  There is a "supplemental" model field now.

**Comment by foxm** [comment]
@queryluke luke, very nice. could you make a couple little modifications, though? take a look at this:

http://localhost:8002/blake/copy/biblicalwc?descId=inscbut519.1.rm.01

the second row of supplemental view handprints (at least on my laptop) lies behind the text 'Supplemental Views'. could you make the supplemental views vertically scrollable so that they don't end up behind that text and partially showing? also, when a supplemental view is showing it should have under it its label. so it would go: handprint, supplemental view label, title of object (which is already showing). 

also, if possible, could you make the original object sit by itself on the first row or first column--probably first row--and smaller than the supplemental view handprints. or better yet, put it in the top left corner of the supplemental view space and make it smaller like this:

Original object        Supp view 1       Supp view 2
(smaller than
supp view
handprints)

                                 Supp view 3      Supp view 4

And then just have the supp view space (not including the original object) be vertically scrollable.

This way the original object is distinguished from the supp views.

**Comment by foxm** [comment]
@queryluke almost! on my laptop the small icon (for the original object) overlaps the first supp view handprint. also, i'd say two for each row is better than three. and the object view space gets resized, throwing off the spacing of the info button. the height of the object view space should probably just stay the same upon moving to a supp view.

**Comment by foxm** [comment]
@queryluke actually, i like the overlap! and the three per row (with the overlap) is fine. it's just the spacing issue when changing between views.

**Comment by foxm** [comment]
@queryluke oh, it's because of "Supplemental Views." i guess we can take that out when viewing a single supp view.

**Comment by queryluke** [comment]
@foxm what size screen is your laptop and what browser are you using. I'm not seeing what you're describing.

**Comment by queryluke** [comment]
@foxm sorry, just pushed over your changes. the "Supplemental Views" text just needed to be included in the overall supp views div, it doesn't need it's own ng-if tag.

**Comment by foxm** [comment]
@queryluke no worries. i think it's all set now. i like how the original object icon overlaps the first supp view handprint. but it only does it if there are enough handprints in that first row. would it be possible to have it overlap that first handprint regardless of how many are in the first row? i have a macbook 13"

**Comment by queryluke** [comment]
it's possible but not an easy task. We'd have to throw more javascript and calculations at it, rather than just straight css.

The left align of the original handprint is set in override.css, line 1162 & 1167 (very bottom), so if you wanted to remove the overlap entirely, you can mess with the values.

**Comment by foxm** [comment]
ok, i changed it into one column. but there are a few issues:

1) the full_object_id for the supplemental view images need to contain the label (Top Mount Inscription) plus the Object number (of the original view image). 

2) when you click the Supp View button while looking at a supp view image, it needs to grab the full_object_id of the original view image so that it can be displayed at the bottom of the gallery window above the tool buttons. right now it retains the full-object_id of the supp view image.

3) is there a way to show the scrollbar upon hovering in the supp view div? right now, it stays hidden until you scroll, which isn't very intuitive.

**Comment by foxm** [comment]
luke, i'm sorry, man. i keep changing my mind on this. i'm thinking now it would be best to just show them all in one row and full size, as in the compare view. that will get rid of all those issues in my previous comment

**Comment by foxm** [comment]
supplemental views \<supplemental\> aren't showing for America B, Europe D, and others

**Comment by queryluke** [comment]
@nathan-rice 

the object_group attribute is null for these. For example: **insceurope.d.rm.01** which is a supplemental of **europe.d.xml**

**Comment by nathan-rice** [comment]
The object group is currently only set for virtual items, as these were initially the only things that it was indicated should be grouped within copies.  Supplemental work should be retrieved separately, using a supplemental-specific data service method.

**Comment by foxm** [comment]
staying with the example, insceurope.d.rm.01.xml should not be used anymore; it's now in europe.d.xml within the \<supplemental\> tag. that tag should be processed just as it is in other works. the supplemental tag is working for some works but not others
