### ISSUE TITLE
affix the static page sidebar menus

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#201]

**Comment by queryluke** [comment]
@foxm have you had a chance to look at these changes

**Comment by foxm** [comment]
@queryluke yeah! sorry, i forgot to respond to this. looks great! i think we just need to fix some of the pages like All Updates. it runs over the text border, and the button highlights change when you navigate to another update.

**Comment by queryluke** [comment]
@foxm the problem with all-updates (and any other funky looking pages) is that they contain their own <html><head><body>etc. tags. They're not really a partial pages.

Looks like each of these html files needs to following the following template
```
<div class="col-sm-9 content-right-column">
  <div class="row">
    <div class="col-sm-12">
      <h2 class="title"> WHATEVER TITLE </h2>
        WHATEVER CONTENT
       <div class="image-right">
         <img src="IMAGE" alt="ALT TITLE" border="0">
      </div>
    </div>
  </div>
</div>
```
