### ISSUE TITLE
image gets elongated when adjusting size of browser

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#203]
the ovp window size changes accordingly when you adjust the size of the browser, but the image size doesn't. its height changes correctly, but not its width

**Comment by queryluke** [comment]
@foxm I'm not seeing this in chrome, firefox, or safari. However, I may have unintentionally fixed it with the new-search-ui branch. I added a new directive to manage heights. Will you check again and let me know. You want to bring down the latest version of master

**Comment by foxm** [comment]
@queryluke it looks like something different might be going on now. it seems when the browser width is below a certain value, the image becomes enlarged. (i'm on chrome).

**Comment by queryluke** [comment]
@foxm yes,many of the responsive features have begun to break down. At some point before a production release, we'll need to look at breakpoints and do some css work.

**Comment by foxm** [comment]
@queryluke yeah, ok, i was thinking the same

**Comment by queryluke** [comment]
closing this as it is related to #207
