### ISSUE TITLE
search only handles single-word queries

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#209]
when you use multi-word queries, no results get returned

**Comment by foxm** [comment]
@queryluke there are still some problems. if i search 'no progression' some titles show up that shouldn't, some transcriptions are showing XML in the results--i assume because 'no' is in '<note>'--as well as results such as 'now' because 'no' is in 'now'. look at the Marriage of Heaven and Hell result in the transcriptions row. i think what we want to be able to do is use quotations in search queries for exact phrases like "no progression." and when not using quotations, the user would expect results ranked according to total hits involving the most number of terms, not total hits of each term.

**Comment by queryluke** [comment]
@foxm I'm moving these into a new issue then. The issue of solr spitting out an error when 2 words were entered is resolved
