### ISSUE TITLE
error in import.py

### ISSUE THREAD

**Issue by queryluke** [blakearchive/archive#210]
@nathan-rice something to look at when you get back from vacation
```
Traceback (most recent call last):
  File "import.py", line 315, in <module>
    main()
  File "import.py", line 303, in main
    importer.populate_works()
  File "import.py", line 90, in populate_works
    self.copies[copy_id].objects for copy_id in virtual_objects.split(",")))
  File "import.py", line 90, in <genexpr>
    self.copies[copy_id].objects for copy_id in virtual_objects.split(",")))
KeyError: u'but1.1'
```

For reference, [this is all I've changed](https://github.com/blakearchive/archive/commit/e0c4fb4f089efae094b75e857a81f6852ca326a7) on import.py

**Comment by nathan-rice** [comment]
This is actually an error introduced by changes in the works.csv.  There is no but1.1.

**Comment by nathan-rice** [comment]
@joeafletch I've verified that neither but1.1 nor but6.1 appear in any of the files in the blake data repository, but you have specified them in the works.csv.  If these files exist, you need to update the data repository to include them.

**Comment by joeafletch** [comment]
@nathan-rice Yeah, they're part of a virtual group of pen-and-ink drawings we published in October, so I'm guessing the data repo hasn't been updated to reflect them--or any of the other pen-and-ink works.
