### ISSUE TITLE
Search result errors

### ISSUE THREAD

**Issue by queryluke** [blakearchive/archive#214]
if i search 'no progression' some titles show up that shouldn't, some transcriptions are showing XML in the results--i assume because 'no' is in '\<note\>'--and some results such as 'now' get returned because 'no' is in 'now'. look at the Marriage of Heaven and Hell result in the transcriptions row. i think what we want to be able to do is use quotations in search queries for exact phrases like "no progression." and when not using quotations, the user would expect results ranked according to total hits involving the most number of terms, then the frequency of terms, not total hits of each term.

**Comment by queryluke** [comment]
@foxm just a follow up on this, the highlights are done on the javascript side of things, not from solr. Thus, the highlight is not an indicator of search precision, rather just an indicator of the search string within the larger text body (transcript, notes, etc)

Either way, highlights (and search results, I think) are showing correctly for phrased and non-phrase searches.

**no progression** returns items with and highlights all occurrences of  **no** or **progression**
**"no progression"** returns and highlights only items with the phrase **no progression**

**Comment by foxm** [comment]
@queryluke this looks good, luke, but for some reason "no progression" is returning a title, illustration description, editors' note, etc., when it should only return a transcription

**Comment by queryluke** [comment]
Thats an issue on the solr indexing end. Making a new issue for it.
