### ISSUE TITLE
search filters operation

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#215]
@queryluke luke, could you take out the search box and make the search results change upon modification of the filters. also, the initial search should include everything as it does now, but changes to the filter should start from nothing. so if a user clicks on a certain type or medium, that type or medium would get checked and searched to the exclusion of all else. and subsequent selections would add to the search results. "Any type" and "Any medium" should be added and initially checked. Have a look at the way google does their image search filters. that bar looks great, by the way

**Comment by queryluke** [comment]
comp and print date don't work, new issue #239

**Comment by foxm** [comment]
@queryluke luke, reopening this one 'cause "Any" for Search Type isn't implemented. it should work the same way as it does for Medium
