### ISSUE TITLE
Erdman User Stories

### ISSUE THREAD

**Issue by joeafletch** [blakearchive/archive#233]
@nathan-rice @queryluke 
Here is the list of top user stories/desired functionality for the Erdman, as discussed by editors and staff at Blake Camp. Let me know if you have any questions.

1. search key words and phrases written by Blake, and their corresponding Erdman page number
2. see the entire sentence or page or work that the searched for word is coming from
3. search for page numbers of quotations, used for checking quotations in essays
4. cut and paste text to use in one’s essays
5. concordance light: to see how often and where Blake used a term; this use may require a display different than the one we are imagining with Google books search display; this might need a list of sentences, what I mean by concordance light. We get that effect with our current Erdman interface within a work, once you turn the triangle to get the nested results to display; but you need to do that for all the works in the hit list
6. to be able to read a whole page or section, like Public Address, online
7. access Erdman’s textual notes​

**Comment by queryluke** [comment]
repeats #133
