### ISSUE TITLE
virtual group issues

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#234]
These virtual groups aren't being treated as groups when they should:
Drawings for Robert Blair's "The Grave" - gravewd
Illustrations to Robert Blair's "The Grave" - gravewc

And ILLUSTRATIONS TO MILTON'S "L'ALLEGRO" AND "IL PENSEROSO" AND DESCRIPTIONS OF "L'ALLEGRO" AND "IL PENSEROSO" DESIGNS (C. 1816-20) should be separated into two groups -- correct me if I'm wrong, but I think this is what we agreed to at BC, right, @joeafletch?

**Comment by queryluke** [comment]
@foxm 

- I just pushed a fix for gravewd. 
- (**gravewc**) Preliminary Illustrations to Robert Blair's "The Grave" is displaying as a virtual group
- (**butwba10**) Did you mean **Illustrations to Robert Blair's "The Grave"**, that is not listed as a virtual group in the [works.csv](https://github.com/blakearchive/archive/blob/master/blakearchive/static/csv/works.csv) file.

- If you need to do any virtual group splitting, that should all be done in the works.csv, you'll need to reseed the database after making changes.

**Comment by foxm** [comment]
@queryluke thanks, luke! and yes, you're right, i mistakenly thought Illustrations to Robert Blair's 'The Grave' was a virtual group. it's missing the copy information. i'll talk to @joeafletch about that.

**Comment by joeafletch** [comment]
@queryluke @foxm Hi guys, I'm back in town now, and ready to pitch in on some of these tasks. Mike, the water color illustrations to Blair's "The Grave" are not a virtual group, but the preliminary illustrations, pencil sketches (gravepd), and wash drawings (gravewd) are. 

And I can modify the works.csv to make the "L'Allegro and Il Pensoroso" water colors and manuscript two separate works. Mike, is there a way I should be doing this other than updating the document in the REDESIGN folder on Blake Drive and then attaching it here?

**Comment by joeafletch** [comment]
@foxm @queryluke for the "l'Allegro and Il Pensoroso" splitting, we're also going to need to change the relational data document since the water color and manuscript objects will now be related to each other via the fourth relational category (reference)--which itself will need to be added as a column to the table--instead of being part of the same virtual group. Mike, if there's a particular document I should be doing this to aside from the "WBARelationalData2.xlsx" in the Redesign folder on Blake Drive, let me know.

**Comment by foxm** [comment]
Hey, joe, you'll have to modify the latest version on github. This can wait, though. I'll set up the repository on your machine after I get back from new york in a few days.

**Comment by foxm** [comment]
Ah yeah, those relational files you can edit since I haven't modified them here. I'll add them here later
