### ISSUE TITLE
search: composition vs print date implementation

### ISSUE THREAD

**Issue by queryluke** [blakearchive/archive#239]
@foxm 
In the search interface, currently there is a checkbox for "Printing Date" and "Composition Date" (which don't do anything). I'm working on implementing these, but need some clarification:

As checkboxes, a user can select both (a boolean OR), i.e., select results with Comp or Print date between X.

Another option is to make these radio buttons. Meaning the user would only be able to limit my comp date or print date, but not both.

Of note, looking at the solr schema's only objects have a print and comp date. So, a filter on just print date will result is 0 copy and work results.

**Comment by foxm** [comment]
@queryluke let's allow for both, so let's use checkboxes

**Comment by queryluke** [comment]
you'll need to reload your blake_work core to prevent errors.
