### ISSUE TITLE
Review solr indexing for search results errors

### ISSUE THREAD

**Issue by queryluke** [blakearchive/archive#241]
I.e. a search for "no progression" returns a title result for Marriage of Heaven and Hell

**Comment by queryluke** [comment]
search "angels sitting"

a transcription result returns correctly, but results in other types like title are being returned when they shouldn't

**Comment by queryluke** [comment]
@nathan-rice, not sure how tricky this will be, but I think the main issue is the components attribute (image tags). Looking at the json, the components are structured like this:

```
{
  "characteristic: [{"#text"}:"example"},{"#text"}:"fake"}]
  "@location": "A",
  "illusobjdesc": "Long text string"
}
```

The issue is `illusobjdesc`. I gets created in line 393-403 in import.py. Can you create a "characteristics" attribute on the object that contains only the values from `characteristic`?

**Comment by nathan-rice** [comment]
It would be fairly straightforward to add an additional field to the object model.  I'm a little confused as to exactly why characteristics needs to be duplicated as a separate field though...

**Comment by queryluke** [comment]
It's a solr search issue. Take the example above. The entirety of the json is stored in the "components" field. So a search for "long" returns the documents. What we really want is to limit the search to everything in "characteristic"

**Comment by nathan-rice** [comment]
Alright, one issue is that characteristics are normally per-component.  Would this characteristic field be one big set of the characteristics from all the components?  Or would it also be broken down by component as a json field?  What would this field be used for?

**Comment by queryluke** [comment]
one big set would be sufficient. no need to keep them broken up by components. The hope to have a single field with all characteristics. This is the field we'd query for image tag results.
