### ISSUE TITLE
the full_object_id values for objects in virtual groups are incorrect

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#261]
first, the full_object_id should not contain the title. we want to use the obj.title field to put the title on a line separate from the object_id (Object 2 (Butlin 435).

second, object numbers should be sequenced (1, 2, 3 ...) according to ascending order of butlin numbers (146, 435, 436), so, for example, water color drawings illustrating the bible,

http://localhost:8002/blake/work/biblicalwc

have the wrong object numbers associated with the butlin numbers. the second object, butlin 435, is labeled object 4. it should be labeled object 2.

and on the object view page under Objects in Group,

http://localhost:8002/blake/copy/biblicalwc?descId=but146.1.wc.01

the order of the handprints is again wrong in a different way.

see here for how they should go: http://www.blakearchive.org/exist/blake/archive/vgroup.xq?id=biblicalwc&java=no&titles=&landing=object&mode=vcopy

i imagine this is an issue with the importing because the object numbers are taken from the full_object_id field.

**Comment by queryluke** [comment]
duplicate/related to #276 & #262
