### ISSUE TITLE
remove text-capitalize class for object.title part of labels

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#274]

**Comment by foxm** [comment]
this is important because the object title is not always capitalized and it needs to be displayed as is. also, we can't use it for letters unless we add exceptions like 'and', 'for', 'to', 'a', etc. i noticed in the letters an object title 'Object 1 And Object 2'. the 'and' shouldn't be capitalized. the best thing to do is to have someone go through and correct the capitalization of these titles, but maybe doing it programmatically is still feasible, given the above

**Comment by nathan-rice** [comment]
Given the title is a property of the data, this is best accomplished by correcting the source data.  On the import end of things, I can pipe data through a title-case function that knows about words like 'and'/'for'/etc; let me know if you would like me to do this, and if so, to which fields specifically.

**Comment by foxm** [comment]
ok, i think the only thing we need to capitalize in the object title during the import stage is the word "object".  that's "object" in the object title (not part of the full_object_id). i know it's confusing.

**Comment by foxm** [comment]
on second thought, "object" in both the object title and the full_object_id should be capitalized. "bentley", "erdman", "keynes", too, although i don't think there are any instances of these in lower case

**Comment by foxm** [comment]
actually, hold off on this. i'm busy fixing this in the data
