### ISSUE TITLE
note for joe f: marriage of heaven and hell copies, first object title

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#283]
@joeafletch 
joe, most of the object titles are transcribed diplomatically, except for the first object of the MHH BADs. should this be fixed?

**Comment by joeafletch** [comment]
@foxm Not sure I follow. How is that first MHH object not being diplomatically transcribed?

**Comment by foxm** [comment]
@joeafletch oh, meant to show the example:

in the BAD we have "The Marriage of Heaven and Hell"
but if we're consistent with other object titles, whose capitalization are retained, i was thinking we should have "THE MARRIAGE of HEAVEN and HELL"

see what i mean?

**Comment by joeafletch** [comment]
Ah okay, yes. This should probably be changed if all other object titles are diplomatically transcribed.
