### ISSUE TITLE
make static sidebar go behind footer when the user scrolls to the bottom of a static page

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#285]
messed around with the z-indexes of the containers for this, but i couldn't get it working

**Comment by queryluke** [comment]
content shouldn't every hide other content, especially navigation. Is there a particular page that is causing issue that I can look at? If so, the better solution would be to providing padding so the nav and footer never touch.

**Comment by foxm** [comment]
About the Archive

**Comment by foxm** [comment]
had a look at this again--realized the sidebar either has to go behind the footer, because the sidebar is fixed, or for the static pages the footer should shift to the right leaving a left column the height of the browser window just for the sidebar. the latter is probably better.
