### ISSUE TITLE
letters object numbers

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#289]
each letter needs to start its object numbering over. so each letter should go Object 1, Object 2, Object 3... this is important because the letter information refers to the objects within each letter by Object 1, Object 2, etc.

a letter is a multiobject work in a virtual group of letters. the letter number is not important, but the object numbers within each letter is important. so we need to come up with a numbering scheme to account for this. letter number and letterpage number--something like that

**Comment by foxm** [comment]
i added code to only show next and previous object icons if next or previous objects exist. it uses the object_number and length of the group to determine if a next or previous object exists. for letters, when we implement them to show all the pages of the letter in the viewer at once side by side, we should show next and previous letter icons using object_number and length of the group of letters. which means that object_number should refer to the letter in the group, and pages within each letter should get their own Object numbers (in some other field) starting from 1.

**Comment by queryluke** [comment]
Is the correct number defined in the BADs?

**Comment by foxm** [comment]
yes, it's \<objnumber\> in the BADs

**Comment by foxm** [comment]
it looks like \<objnumber\>Object 1 \</objnumber\>. notice that space at the end that shouldn't be read

**Comment by queryluke** [comment]
@nathan-rice 

Looking at what get's imported, we should be able to use the full_object_id. But currently, some full_object_id's are empty. I can't seem to find a patter.

```lt10november1825.1.ltr.01``` has no full_object_id, but ```lt10november1825.1.ltr.02``` has "Object 2"

```lt12april1827.1.ltr.02 - 04``` all have full_object_ids, ```01``` does not.

And there are some sets with no full_object_ids
```lt11oct1825.1.ltr.01``` & ```lt11oct1825.1.ltr.02```

**Comment by nathan-rice** [comment]
full_object_id for the first object of each copy in a virtual group is currently being set to an empty string.  This was requested behavior.

**Comment by foxm** [comment]
hmm, i'm not sure why we would have requested that
