### ISSUE TITLE
ordering for handprints under objectsfromsame tabs

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#291]
by printdate[@value], then compdate[@value], then copy designation. 

@joeafletch can confirm this. joe, the objectsfromsame tabs include all the related tabs. on the current site, the same matrix objects are ordered by printdate[@value], then copy designation, and the other related items aren't ordered but probably should be by the above sequence, right?

**Comment by foxm** [comment]
@queryluke the printdate[@value] doesn't seem to be available in the object model for objects. i see copy_composition_date but not copy_print_date

**Comment by queryluke** [comment]
closed with #262

**Comment by foxm** [comment]
it turns out the way objectsfromsame need to be sorted not by print date value > composition date value > object number, but by only composition date value > object number. the reason for this is that sometimes objects don't have print dates and we can't mix comp dates and print dates in an ordering
