### ISSUE TITLE
indent <note>s in copy information

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#294]
the note, if displayed right, refers to the field and value above it. indenting it will make that known

**Comment by queryluke** [comment]
@foxm All the notes are marked with class"indent-dl", you can adjust their styling and left margin in overide.css if you want to make additional aesthetic changes.

**Comment by foxm** [comment]
@queryluke ok, i made notes bullet points with \<li\>, so when we add those other notes, they should also be made bullet points
