### ISSUE TITLE
print/composition_date_string remove <note>

### ISSUE THREAD

**Issue by queryluke** [blakearchive/archive#297]
The ```<note>``` tag is being parse in the copy print/composition_date_string attributes. Should be removed.

**Comment by foxm** [comment]
fixed with the code below from import.py. if there's a better way, we can roll back this change.

`def get_compdate_string(self, document):
        for cd in document.xpath("//compdate"):
            return str(cd.xpath("text()")).strip("'[]'").rstrip().encode("utf-8")

    def get_printdate_string(self, document):
            for pd in document.xpath("//printdate"):
                return str(pd.xpath("text()")).strip("'[]'").rstrip().encode("utf-8")`
