### ISSUE TITLE
in copy information, if a field is empty, don't show the field name

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#300]

**Comment by queryluke** [comment]
I think the latest commit I made should have fixed this. It checks if a specific ```fieldname["#text"]``` exists, if not, it won't render the list item.

**Comment by foxm** [comment]
nice. i noticed that the Present Location section is a little off, and it might be a problem with the source. the fax, email, and url fields are mixed up. have a look at the Object Information for this:

http://localhost:8002/blake/copy/gravepd?descId=but614r.1.penc.01

i see the parsing going on in the code. i can look at this more closely tomorrow

**Comment by queryluke** [comment]
I didn't change the present location pieces, they're still rendered as they were before I introduced the new directive.

But I can see the problem. The xml doesn't have tags for those fields. It looks like it all gets stored in a multiline ```<addressline>``` tag.

The code is splitting the contents of ```<addressline>``` on the colon. Then rendering the latter half. I just pushed an update to render the front half of the split, but some of those are really long, e.g. **Telephone, Photography and Rights Department:** And are getting cut off by the css.

Not sure if you want that additional info. If not, I'd say you should edit the BADs, keeping telephone and email info in an ```<addressline>``` tag doesn't make sense to me. Rather should be something like ```<telephone>123-45-6789<department>Photograph and Rights</department></telephone>```
