### ISSUE TITLE
to form copy_title, if no <copy> tag, use 'copy' attribute of <bad> tag

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#308]
i think the reason why it's missing is because this work (BB136.A) has an archive_copy_id (A) but no <copy> tag in its BAD. i imagine there are more like this

**Comment by foxm** [comment]
yes, there are several instances of this issue. copy_title for these instances needs to include "Copy X" where X is the value of the "copy" attribute of the \<bad\> element

**Comment by queryluke** [comment]
Is this resolved?

Looking at http://localhost:8002/blake/copy/bb136.a?descId=bb136.a.spb.01
and http://localhost:8002/blake/work/bb136, the title of the copy is "Copy A".

"A" is the value of the <bad> copy attribute in BB136.A.xml

**Comment by foxm** [comment]
hmm, yeah, it looks like it. i guess nathan must have resolved it. don't know. strange. gonna keep the issue open for a bit in case it crops up.
