### ISSUE TITLE
objectsfromsame ordering

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#314]
objectsfromsame need to be ordered by print date value (if print date value) or comp date value (if not print date value), then object number. sometimes there a mix of objects with print date values and objects with only comp date values. this we'll make clear in the labeling

**Comment by foxm** [comment]
for example: http://localhost:8002/blake/copy/mhh.c?descId=mhh.c.illbk.21

Objects with a Similar Design shows Illustrations to Robert Blair's the Grave, 1805 at the end. 1805 is the comp date value for that object. it doesn't have a print date value. and it should be ordered with the rest of the objects that have print date values

**Comment by foxm** [comment]
maybe an objectsFromSameOrderBy field would help. it would contain the print date value if it exists or the comp date value if the print date value doesn't exist. this scheme is only for the objectsfromsame tabs

**Comment by queryluke** [comment]
@nathan-rice as discussed 8/10, please make a computed column on the object model. It should be populated with the print date or comp date if print date is null. All objects from same X queries need to be sorted by this new computed column

**Comment by foxm** [comment]
print date value or comp date value if print date value is null, just to be clear

**Comment by foxm** [comment]
i saw the latest commit for this and made a slight revision: the fix uses comp and print date value, not comp and print date. and, @queryluke i fixed the Objects from Copy tab for this, but and i imagine the other instances of filter:{supplemental:null} will have to be revised to get the supplemental objects showing. i'll leave this one to you because i'm not sure what the fix entails
