### ISSUE TITLE
relations for http://localhost:8002/blake/copy/biblicalwc?descId=but435.1.wc.01

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#318]
@joeafletch something still seems off with:
http://localhost:8002/blake/copy/biblicalwc?descId=but435.1.wc.01

we can have a look the next time you're in. i'm just recording this before i forget

**Comment by joeafletch** [comment]
Hey @foxm I'm unable to access that link off campus, even using the VPN. Anything I can do?

**Comment by foxm** [comment]
@joeafletch ah, that's a link to my local setup. but nevermind, i just verified the relation tabs against the relations shown on the current site. they look correct
