### ISSUE TITLE
auto scroll to object when opening reading mode 

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#319]
when moving from an object in object view to reading mode or from virtual work object on work page or on overlay, auto scroll to that object

**Comment by foxm** [comment]
this is not a priority, but one of the editors, Bob, noticed it while he was testing, so if we have time to get to it, that would be great, but if not it's ok.

**Comment by foxm** [comment]
@queryluke i'm stumped on this one. i tried putting in an id for each object (o.desc_id):

```
<div id="o.desc_id" class="item" ng-repeat="o in read.bds.copyObjects | filter:{supplemental:null}" ng-if="read.bds.copy.bad_id != 'letters'">
                <div class="reading-wrapper" auto-height adjust="150" breakpoint="768">
                    <img ng-src="/images/{{ o.dbi }}.100.jpg" ng-click="read.changeObject(o)">
                    <div class="reading-copy">
                        <div class="reading-copy-inner">
                            <h4 ng-if="o.title" ng-click="read.changeObject(o)">{{o.title}}<br><span class="text-capitalize">{{ o.full_object_id }}</span></h4>
                            <h4 ng-if="!o.title" ng-click="read.changeObject(o)"><span class="text-capitalize">{{ o.full_object_id }}</span></h4>
                            <text-transcription object="o"></text-transcription>
                        </div>
                    </div>
                </div>
            </div>
```

and then in the js, i added an $anchorScroll() scope function to run after content is loaded:

```
$scope.$on('$viewContentLoaded', function(){
            var newHash = 'anchor' + vm.descId;
            if ($location.hash() !== newHash) {
                $location.hash('anchor' + vm.descId);
            }
            else {
                $anchorScroll();
            }
        });
```

didn't work. i wonder if it has something to do with the window being horizontally scrollable

**Comment by queryluke** [comment]
$anchorscroll is just a tap into the default browse anchor behavior. And, as far as I know, browsers don't scroll horizontally  to get to an anchor. Only vertically. But I could be wrong.

In term's of code `var newHash = 'anchor' + vm.descId;`, means the resulting #id the code looks has the string `anchor` in front of it. but your id is just `o.desc_id` not `anchor{{o.desc_id}}`, also note the curly braces, otherwise your just rendering the string `o.des_id`

**Comment by foxm** [comment]
ah, i see. 

ok, well, if $anchorScroll won't work horizontally--i think i read that somewhere else, too--then we'll have to figure out something else anyway.

**Comment by foxm** [comment]
very nice, luke, but one thing broke: you can't switch to reading mode now from the homepage

**Comment by foxm** [comment]
sorry, i wasn't clear. if in Reading Mode, clicking on a featured object from the homepage, should open the reading view scrolled to that object

**Comment by foxm** [comment]
hmm, i don't think this is working from the homepage

**Comment by foxm** [comment]
@queryluke luke, i see why this is kind of difficult. if you click on a featured object from a work with many objects, the scroll happens during the load and doesn't go far enough. for example:

http://london.lib.unc.edu/blake/copy/jerusalem.e?descId=jerusalem.e.illbk.32

although, to see this example, you'd have to click on the that object from the homepage

**Comment by foxm** [comment]
i guess it works as good as it can. i just hope with the minifying, everything will be much faster
