### ISSUE TITLE
full_object_id for virtual group object in search results is off

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#326]
search 'angel'

under Water Color Drawings Illustrating the Bible in the first row, notice how all the matching objects are labeled "Object 1"

those three should be Object 16, 55, and 58

**Comment by foxm** [comment]
@queryluke luke, i think maybe the letter object fix--which is great, thank you--might have broken this. not sure. but the full_object_id everywhere else contains the right Object number along with Bentley number, Erdman number, etc., or Butlin number. for virtual groups, the full_object_id seems to be correct everywhere except in the search results.

**Comment by queryluke** [comment]
@foxm I'm still using javascript to number virtual work objects. Which I can't do for search results because I need to cycle though all objects to assign the correct numbers.

A temporary solution would be to use the object title for virtual group objects, since they each have unique titles.

**Comment by foxm** [comment]
ok, good idea. fixed
