### ISSUE TITLE
Supplemental Views/Inscriptions

### ISSUE THREAD

**Issue by joeafletch** [blakearchive/archive#339]
I think this issue was removed, but there are still some problems with the navigation of this feature on London. When I click on the supplemental view button, for, say, object 1 of _America_ copy B, I get the vertical array of supplemental objects. I can click on these and get to the OVP for the supplemental image, but once there it's unclear how I get back to the original "normal" view of object 1, except by scrolling down to the "Objects in Copy" tab. I thought there was going to be an easier way to get back to that column of supplemental images, or back to the original OVP.

**Comment by foxm** [comment]
just noticed now that this seems to be only a problem on london. an initial click of a supp view item takes you back to the original item and a subsequent click removes the supp view button.

but on my local setup, everything works as it should
