### ISSUE TITLE
homepage images sometimes don't fill up the whole space

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#343]

**Comment by queryluke** [comment]
@foxm I don't have a large screen so I can't adjust the css to fix this. See my documentation on the previously closed issue:

https://github.com/blakearchive/archive/issues/123

Right now, that css is around line 390 in `overide.css`. You can adjust the values in the `@media (min-width: 1200px)` block for vary large screens. 

Or if you need another breakpoint make a new block:
```
@media (min-width: 1440px){
    #home.container-fluid.main .row div[class^="col-"] {
        max-width: 500px;
        max-height: 950px;
    }
}
```
I arbitrarily chose **1440,500, and 950**. You'll need to adjust them based on how things look on your screen.

**Comment by foxm** [comment]
haven't seen this problem crop up in a while
