### ISSUE TITLE
transition image paths to local env

### ISSUE THREAD

**Issue by queryluke** [blakearchive/archive#349]

**Comment by queryluke** [comment]
made a branch for this, want to test it in Nov 16 meeting.

**Comment by queryluke** [comment]
@foxm now that images are in place, you'll need to rsync the image directory down to your local machine and add a line to your config file. I put some information in the readme

**Comment by foxm** [comment]
@queryluke ok, where should i put the local image directory so that it doesn't get pushed to the repo?

**Comment by foxm** [comment]
@queryluke oh, blake/archive?

**Comment by foxm** [comment]
@queryluke sorry, nevermind, luke. i'll just put them outside of the project altogether

**Comment by foxm** [comment]
@queryluke in config.py, what do i name the image dir variable?

**Comment by queryluke** [comment]
@foxm you can put it wherever you want. and the var name is local_image_path

**Comment by queryluke** [comment]
that's my fault, I had the wrong var name in the config.py.example

**Comment by foxm** [comment]
@queryluke perfect, thanks. one thing to note--you have to put the '/' at the end of the path
