### ISSUE TITLE
image in gallery window gets elongated when you manually resize the browser window

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#353]

**Comment by queryluke** [comment]
I need an example. This seems to be working for me

**Comment by foxm** [comment]
all of them. if you stretch the window, you'll see the image become elongated. hit reload (after stretching the window) to see the image resize to its correct proportions.

**Comment by foxm** [comment]
i think maybe it's more apparent on joe's large monitor. we can show you tomorrow.

**Comment by foxm** [comment]
unfortunately that other commit didn't fix this. the image is still getting elongated. try just stretching horizontally. you should be able to replicate it that way.

**Comment by queryluke** [comment]
Is this still an issue? I've checked at home on a 27". I'm looking at:

http://blake-qa.lib.unc.edu/blake/copy/bb85.a?descId=bb85.a.spb.07


1. Window is at full size. Reload page. Image size: **396x549**
2. Hover over the right edge of the browser window, grab the edge and slowing drag it it in (making the window smaller).

The image is remaining the same size until the tablet breakpoint, at which point it get's slightly larger, but still proportioned. **422x585**

3. From the tablet size, hit reload **422x585**
4. Slowly drag the right side of the broswer window (making it larger)

When the image hits the small screen breakpoint it gets slightly smaller, but it's still proportioned. As I drag it further out, the image remains the same size. **396x549**

5. Hit relaod, image size **396x549**

396/549 = .721311
422/585 = .721367

So there might be a very minor alteration. But hitting reload doesn't' fix it.

If it's still happening on a large screen, can you get me the dimensions and resolution of that screen?

**Comment by foxm** [comment]
i don't think it's an issue anymore. i tried to replicate this the other day. if it crops again, we can fix it later
