### ISSUE TITLE
changes to static pages don't get picked up on qa or prod after deploy

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#354]

**Comment by foxm** [comment]
@queryluke luke, i had to modify the line below in qa.rb to get this to pick up the changes. python26 was 2 behind and 42 ahead of master somehow.

                execute "cd ../archive; git checkout master; git pull origin master; git checkout python26; git pull; git merge --no-ff -m 'Merge master into python26' master; git push origin python26; git checkout master;"

i added in that 'git pull' after 'git checkout python26.' is that all right? i've committed the change, but if you think it'll screw things up, of course feel free to revert it.

**Comment by foxm** [comment]
@queryluke actually, i just tried to commit the change to qa.rb, but i don't have permission to do so. can you give me permission?

**Comment by queryluke** [comment]
With capistrano, you need to commit your changes to the github repo first. So if you made some changes locally, then ran the deploy scripts, they wouldn't have shown up on qa or prod. But when you commit them to github, then run deploy, they'll show up.

Concerning python26 branch, it will always be ahead of master. It will be behind master until there is a deploy.

However, as I work on things this week, I'll monitor this just to make sure everything is working as intended.

**Comment by foxm** [comment]
@queryluke yes, i'm aware. in this case, i had committed the local changes, and the deploy scripts didn't pick them up. i had to modify qa.rb, adding 'git pull' after checking out python26. but i can't commit the change to qa.rb (no permission). can you give me permission to commit to archive-deploy?

**Comment by queryluke** [comment]
The deploy reacts to what's in the github repo, not what's on your local machine. So running git pull there doesn't really do anything. The command after that updates python26 with everything in master.

If you review python26's commit history, you'll see the changes were sticking, e.g.
https://github.com/blakearchive/archive/commit/e4a9be82e2f83d5cf30daba3fce873d54399013d

Could have been a caching issue as well. I've noticed that my updated chrome browser is much more aggressive with caching.

Again, I'll be monitoring this.

**Comment by foxm** [comment]
@queryluke i modified qa.rb by adding 'git pull' to it. i thought that meant the 'git pull' was being run on the qa server, not my local machine.

definitely wasn't a cache issue. i cleared my cache. i think the problem was that python26 somehow got out of sync with the python26 repo.

**Comment by foxm** [comment]
@queryluke i can't replicate the problem now, but i remember seeing red error lines in the debug log when running the deploy, indicating a problem with pytho26 and recommending doing a 'git pull.' so i added 'git pull' to qa.rb. anyway, that fixed it, but i can't commit the change.

can you give me permission to commit to archive-deploy? thanks.

**Comment by foxm** [comment]
@queryluke in my office now. same problem cropped up. below is the relevant log from the deploy. the solution again was to add 'git pull' after checking out python26 to qa.rb.

i need permission to commit to archive-deploy. you seem hesitant to give it to me. perhaps for security reasons? if so, i don't see why--regardless of whether or not i can commit to archive-deploy, i can still edit the scripts and run remote commands. if you can't give me permission to commit to archive-deploy, then i'm just going to make my own repo for it and start using that one.

 [d1d23ca7] 	Already on 'master'
DEBUG [d1d23ca7] 	Your branch is up-to-date with 'origin/master'.
DEBUG [d1d23ca7] 	From https://github.com/blakearchive/archive
DEBUG [d1d23ca7] 	 * branch            master     -> FETCH_HEAD
DEBUG [d1d23ca7] 	Already up-to-date.
DEBUG [d1d23ca7] 	Switched to branch 'python26'
DEBUG [d1d23ca7] 	Your branch is behind 'origin/python26' by 10 commits, and can be fast-forwarded.
DEBUG [d1d23ca7] 	  (use "git pull" to update your local branch)
DEBUG [d1d23ca7] 	Removing gulpfile.js
DEBUG [d1d23ca7] 	Removing blakearchive/static/dist/main.min.js
DEBUG [d1d23ca7] 	Merge made by the 'recursive' strategy.
DEBUG [d1d23ca7] 	 .../static/controllers/staticpage/meta.json        |   1 +
DEBUG [d1d23ca7] 	 blakearchive/static/css/override.css               |  14 ++
DEBUG [d1d23ca7] 	 .../directives/info-tray/infoTray.directive.js     |   4 +-
DEBUG [d1d23ca7] 	 .../directives/search-results/searchResults.html   |   2 +-
DEBUG [d1d23ca7] 	 blakearchive/static/dist/main.min.js               |  37 ---
DEBUG [d1d23ca7] 	 blakearchive/static/html/abouteditors.html         |  23 +-
DEBUG [d1d23ca7] 	 blakearchive/static/html/advisoryboard.html        |  31 ++-
DEBUG [d1d23ca7] 	 blakearchive/static/html/biography.html            | 266 ++++++++++-----------
DEBUG [d1d23ca7] 	 blakearchive/static/html/projectteam.html          |  22 +-
DEBUG [d1d23ca7] 	 .../static/html/sponsorsandsupporters.html         |  35 +++
DEBUG [d1d23ca7] 	 blakearchive/static/js/main.js                     |  39 +--
DEBUG [d1d23ca7] 	 gulpfile.js                                        |  22 --
DEBUG [d1d23ca7] 	 12 files changed, 238 insertions(+), 258 deletions(-)
DEBUG [d1d23ca7] 	 delete mode 100755 blakearchive/static/dist/main.min.js
DEBUG [d1d23ca7] 	 create mode 100644 blakearchive/static/html/sponsorsandsupporters.html
DEBUG [d1d23ca7] 	 delete mode 100644 gulpfile.js
DEBUG [d1d23ca7] 	To https://github.com/blakearchive/archive.git
DEBUG [d1d23ca7] 	 ! [rejected]        python26 -> python26 (non-fast-forward)
DEBUG [d1d23ca7] 	error: failed to push some refs to 'https://github.com/blakearchive/archive.git'
DEBUG [d1d23ca7] 	hint: Updates were rejected because the tip of your current branch is behind
DEBUG [d1d23ca7] 	hint: its remote counterpart. Integrate the remote changes (e.g.
DEBUG [d1d23ca7] 	hint: 'git pull ...') before pushing again.
DEBUG [d1d23ca7] 	hint: See the 'Note about fast-forwards' in 'git push --help' for details.
DEBUG [d1d23ca7] 	Switched to branch 'master'

**Comment by queryluke** [comment]
I see the problem. Git pull is fine. The other option is running git fetch before anything else. Resulting in the following. 
```
execute "cd ../archive; git fetch; git checkout master; git pull origin master; git checkout python26; git merge --no-ff -m 'Merge master into python26' master; git push origin python26; git checkout master;"
```

Git fetch will update all your local branches with their remote counterparts, but not override any work you've done on them. So it might be safer than git pull. But both should work.

**Comment by foxm** [comment]
makes sense. thanks, luke
