### ISSUE TITLE
color prints groupings

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#357]
http://localhost:8002/blake/copy/cpd?descId=but327.1.cprint.01

the large color printed drawings virtual group contains subsets of similar objects. for example, there are three "Christ Appearing to the Apostles After the Resurrection." these are like 'copies' as we define other copies, but they need to be grouped and made comparable. 

we'll need to think of the best way to do this visually and programmatically.

**Comment by foxm** [comment]
one solution:

order this group by Butlin number (that will order them properly)
update blake-relations.csv to reflect the groups of 'copies'

**Comment by foxm** [comment]
it looks like blake-relations.csv has these relations; they're just not getting picked up

**Comment by foxm** [comment]
here are the relevant entries for the example of "Christ Appearing to the Apostles After the Resurrection" in blake-relations.csv:

but325.1.cprint.01,BUT325.1.1.CPD,but325.1,cpd,"but326.1.cprint.01,but327.1.cprint.01",,,,,,
but326.1.cprint.01,BUT326.1.1.CPD,but326.1,cpd,"but325.1.cprint.01,but327.1.cprint.01",,,,,,
but327.1.cprint.01,but327.1.1.CPD,but327.1,cpd,"but325.1.cprint.01,but326.1.cprint.01",,,,,,

**Comment by queryluke** [comment]
I'll have to have Joe explain this to me. When I look at http://london.lib.unc.edu/blake/copy/cpd?descId=but327.1.cprint.01 and click on Objects from the Same Matrix, I see 2 other "Christ Appearing to the Apostles After the Resurrection"

**Comment by foxm** [comment]
oh, yes, of course. i had gotten confused when joe v. brought this up. it's working as it should. closing...
