### ISSUE TITLE
Duplicate editor's notes

### ISSUE THREAD

**Issue by queryluke** [blakearchive/archive#366]
Split from #355

**Comment by queryluke** [comment]
@joeafletch see http://london.lib.unc.edu/blake/copy/mhh.e?descId=mhh.e.illbk.06 (Editors Notes)

@foxm was questioning "duplicate" notes. Is this something I need to look into, or do the BADs have the duplication

**Comment by foxm** [comment]
@queryluke the note is showing up similarly twice in the BAD, not three times. once for object and once for the line in the text. each one is slightly different. that's deliberate. but it looks like what's happening is that the object note is getting repeated in the textual note.
