### ISSUE TITLE
Virtual group object urls are malformed

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#371]

**Comment by queryluke** [comment]
Do you mean this http://localhost:8002/blake/copy/cpd?descId=but324.1.cprint.01 ?

Remember, works that are part of a virtual group have different urls that regular objects.

**Comment by foxm** [comment]
@queryluke  ah, ok. that means the url is being generated incorrectly for handprints of objects from virtual groups. if you go to http://london.lib.unc.edu/blake/copy/mhh.c?descId=mhh.c.illbk.04 and then to Objects with a Similar Design and click on one of those handprints, you'll notice they don't come up because the url (i guess) is being generated incorrectly

**Comment by queryluke** [comment]
@nathan-rice can you look into this. I'm getting inconsistencies in the data so I think something is happening in the import script.

The problem only exists for virtual works. Take the following: http://london.lib.unc.edu/blake/copy/biblicalwc?descId=but146.1.wc.01

the underlying copy "biblicalwc" has bad_id = "biblicalwc". (It's copy_id is 28, if you want to look it up in the DB)

However all of the objects do not have a matching "copy_bad_id". For example, the selected object in the link above shows a copy_bad_id of "but146.1".

Looking at the import scripts, line 267, `obj.copy_bad_id = copy.bad_id`, so I'm not sure how this is getting out of sync.
