### ISSUE TITLE
robert blair, the grave missing representative handprint in search results

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#373]
to get it as a result, search 'good evil angels', go down to Work row.

**Comment by foxm** [comment]
it should match up with the representative handprint on the work info page. i checked copy-handprints.csv for bb435. looks good, so i'm not sure what's going on.

http://london.lib.unc.edu/blake/work/bb435

**Comment by queryluke** [comment]
But that's a work result. So it needs to have a representative image in the works.csv file (data/csv/works.csv)

Right now, line 64 of that file has: `b435.1.1.com.100.jpg` as the image. But http://london.lib.unc.edu/images/b435.1.1.com.100.jpg doesn't exist on the server. I see a `but435.1.1r.wc.100.jpg`

Either way the works.csv file needs to be updated. Then reimport.

**Comment by foxm** [comment]
ah, right, ok all set
