### ISSUE TITLE
Virtual group object labeling

### ISSUE THREAD

**Issue by joeafletch** [blakearchive/archive#385]
@nathan-rice To get the labeling correct for virtual group object handprints under objects_from_same tabs, we need to add a new field to the object model: virtual (boolean). That way, users will be able to see the objects by their virtual group title as well as their work title (which in this case is their object title)--so they'll have a better sense of what they're looking at under those tabs. Thanks.

**Comment by foxm** [comment]
i just realized we'd also need a virtual group title field for the Object model

**Comment by foxm** [comment]
@queryluke since there's just this last one left--do you think you could take a look? i can fix up the labeling once it's ready

**Comment by queryluke** [comment]
Looking at the import code, objects get a few attributes from the copy, but it doesn't look like copies or objects get any attributes from work. So it's not as simple as adding onto code thats already there. I'm sure I could figure it out, but I'm about to drive home and won't be able to work for the next 4 hours. We're just going to have to let this one slide.

**Comment by foxm** [comment]
Ok, sounds good, thanks

**Comment by ba001** [comment]
fixed
