### ISSUE TITLE
main menu broke

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#388]
@queryluke luke, i think your last commit might have broken the main menu

**Comment by joeafletch** [comment]
I don't know if I'm doing something wrong, but the main menu isn't working for me again, even after I emptied my cache.

**Comment by foxm** [comment]
@queryluke not sure how this broke again. a recent commit maybe? i see this error in the console:

angular.min.js:107 TypeError: Cannot read property '0' of undefined
    at http://localhost:8002/blake/static/directives/menu/directive.js:122:74
    at Array.forEach (native)

**Comment by queryluke** [comment]
The issue was commenting out the exhibits, the case statement needs to be removed as well
