### ISSUE TITLE
client ppi presets correspond to incorrect lengths

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#389]
the true size presets are off.

i have an iMac 27". when i click on it, the right settings get filled in, but the red line is two and half inches long, not one inch. i imagine it's off for all the presets.

**Comment by foxm** [comment]
fixed

**Comment by queryluke** [comment]
I pulled your change and checked on 4 different monitors, they were all incorrect. Then I put the code back to where it was and checked again. It's working without fail for me.

There are some reasons why you may have seen a longer line:

First, there are 2 iMac 27" options. Notice one has a much higher resolution. If you accidentally selected the higher resolution one, then the line would have been much longer.

Second, even if you selected the correct iMac 27", doesn't mean you're running the standard resolution. If you open up your system preferences > displays, then hover your mouse over your selected option, you'll see the resolution you need you use.

**Comment by foxm** [comment]
ah, ok. i'll check.
