### ISSUE TITLE
links in letters info file

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#390]
links in letters info file need to be rendered. for example:

`<link type="object" ptr="lt1827.1.ltr.02">(object 2, lines
                6-9)</link>`

**Comment by foxm** [comment]
not a priority, but if we can get to this, it would help

**Comment by foxm** [comment]
these are links within the info field, not the title field of the Related Works

**Comment by foxm** [comment]
these are links of type object in the `<relationship>` tags

**Comment by queryluke** [comment]
Sadly, I can't do anything about this. The link information is not stored in the database. Nathan will need to update the import scripts.

**Comment by joeafletch** [comment]
@foxm Did the letters info file get changed? I know the links weren't working, but now the related objects in the letters aren't being listed under the works. The "All Known Related Items" list now shows only a list of related works with no further information (which was showing up a couple days ago).

**Comment by foxm** [comment]
@queryluke the only change was the *'s i think
