### ISSUE TITLE
Give textual notes line numbers

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#394]
@queryluke markdown seems to have cause a problem in the editors' notes.

look here:
http://london.lib.unc.edu/blake/copy/america.b

the first strangely rendered set of lines are an object note and should be in the object note section of editors' notes. they are here in the XML:
```
<objnote>
          <p>There are two inscriptions and a drawing, not by Blake, on the verso of Object 1; see Related Works in the Archive.</p>
        </objnote>
```

also, the textual notes don't make sense without the line number. in this example:

the line number is '04'
```
<lg justify="left">
          <l justify="left" n="relamerica.b.rm.01.04">Mary Taylor London
            <note>This inscription, not by Blake, appears vertically at lower left.</note></l>
        </lg>
```

so, the entry should say something like 'Line 04: This inscription, not by Blake, appears...'

**Comment by foxm** [comment]
i think part of this issue has to do with this being an object with Supplemental Views

**Comment by queryluke** [comment]
fixed with the trim() changes

**Comment by foxm** [comment]
looks great, luke. i'm just reopening because we still have to figure out the Textual Notes at some point.  the textual notes always correspond to a line number, and in the example below, some of them correspond to a different supplemental view

from a previous comment:

also, the textual notes don't make sense without the line number. in this example:

the line number is '04'

```
<lg justify="left">
          <l justify="left" n="relamerica.b.rm.01.04">Mary Taylor London
            <note>This inscription, not by Blake, appears vertically at lower left.</note></l>
        </lg>
```
so, the entry should say something like 'Line 04: This inscription, not by Blake, appears...'

**Comment by queryluke** [comment]
The line context doesn't exist in the data model. If you look at an object (in developer mode), there is a single attribute `notes`, which is just an array of notes. Without any other context I won't be able to do anything. This is probably something Nathan will need to adjust in the import scripts

**Comment by foxm** [comment]
@queryluke ok, for now maybe we could just put the 'Line X' in the note itself. a regex search and replace might do the trick

**Comment by queryluke** [comment]
I'm going to attempt to tinker with the python scripts, I may break some things. But hold off for right now

**Comment by queryluke** [comment]
Should be done now

**Comment by foxm** [comment]
@queryluke luke, great job. reopening just because that weird rendering cropped up again:

http://london.lib.unc.edu/blake/copy/america.b?descId=america.b.illbk.04

**Comment by queryluke** [comment]
It's the `<lb/>` tag in the BAD. The markdown parser doesn't know what to do with those.
```
<p>This object is a lithographic reproduction not by Blake; see Copy Information for details.  Five lines of verse etched on the copperplate following line 17 were masked during printing in Copies B-F, H-M, R, and a.  These lines were erased after printing in Copy G (Bentley page 94).  These lines, printed in Copies A, N-Q, read:
            <lb/>
            <lb/>
            The stern Bard ceas'd, asham'd of his own song; enrag'd he swung
            <lb/>
            His harp aloft sounding, then dash'd its shining frame against
            <lb/>
            A ruin'd pillar in glittring fragments; silent he turn'd away
            <lb/>
            And wander'd down the vales of Kent in sick &amp; drear la-
            <lb/>
            mentings.</p>
```

**Comment by foxm** [comment]
also, now that you've made this fix, would it be easy to make the line numbers in the transcription linked to their textual note? if not, don't worry about! we can do that later

**Comment by foxm** [comment]
oh, those are line breaks because of the poem's lineation. hmm

**Comment by queryluke** [comment]
RE linking line notes: This is the first step towards that, but it only get's us halfway there. The entirety of the text_transcription gets parsed through the XSLT transformer. So when it gets into the database, it's just a big blob of HTML which I can't do anything with. To achieve the line note links, there will need to be a lot of additional python scripts to process poem lines.

RE the `<lb />`, you should be able to use simple carriage returns

**Comment by foxm** [comment]
i got ya, about the linking. 

ok, i'll test out the carriage returns.

**Comment by foxm** [comment]
worked
