### ISSUE TITLE
illustration descriptions are missing info

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#396]
@queryluke @joeafletch see this on the current site:

http://www.blakearchive.org/exist/blake/archive/illusdesc.xq?objectid=thel.d.illbk.08&objectdbi=thel.d.p8

and on the new site under Illustration Description in info box:

http://london.lib.unc.edu/blake/copy/thel.d?descId=thel.d.illbk.08

they don't match up. the main Plate Illustration is missing, and the first line (Sector CD) is not a constant. but for now we can just take that line out. in the future, we need to fix up the Illustration Description to distinguish between Interlinear Illustration, Plate Illustration, etc.

**Comment by foxm** [comment]
@queryluke hmm, actually now the illustration description content isn't showing at all. might have broken with the fix you made for the editors' notes

**Comment by queryluke** [comment]
@foxm I've been working on this issue is why they aren't showing up

**Comment by foxm** [comment]
yes!
