### ISSUE TITLE
repeat in editors' notes

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#399]
there's a repeat under Object in editors' notes here:

http://london.lib.unc.edu/blake/copy/america.b?descId=america.b.illbk.01

also, this a case where there are supplemental views. the notes are supposed to correspond to particular views

**Comment by foxm** [comment]
so those textual notes are actually for different supplemental views

**Comment by queryluke** [comment]
I'm in the car so I can't deploy this, but I've just updated the import script. Can you deploy and let me know if that fixed it?

**Comment by foxm** [comment]
hmm, no, it looks like notes aren't coming up at all now

**Comment by queryluke** [comment]
import.py, line 453

`for note in obj.xpath(".//note") + obj.xpath(".//objnote"):`

xpath is a way of selecting nodes out of an xml structure.  Right now, the current code `.//note` and `.//objnote` selects ALL descendant `<note>` and `<objnote>` nodes.

Since `<supplemental>` is nested below `<desc>` any `<note>` or `<objnote>` within `<supplemental>` are getting slurped into the parent `<desc>`.

So we need an xpath selector to not target anything in `<supplemental>` . I'll do some browsing and see what I can find

**Comment by queryluke** [comment]
Or instead of figuring out not logic, are all notes under a specific element? `<physdesc>` and `<phystext>`? If so you could change that line to:

`for note in obj.xpath("./phystext//note") + obj.xpath("./physdesc//objnote"):`

If you want to try that and see what happens.

**Comment by foxm** [comment]
that seems to have worked! except now i'm getting that damn strange rendering again in the notes:

http://london.lib.unc.edu/blake/copy/america.b?descId=america.b.illbk.04

i put in double carriage returns between those lines from the quoted verse in the note

**Comment by queryluke** [comment]
I've been doing some tinkering. If you ever want to know what the resulting markdown will look like, copy the text into a github issue and hit preview.

For example, in the comment section below, hit the space key more than 4 times then type something then hit preview. Markdown translates this into a **code** section (for whatever reason)

So what was happening in the code:
```
<note>Five lines of verse etched on the copperplate following line 17 were masked during printing in Copies B-F, H-M, R, and a.  These lines were erased after printing in Copy G (Bentley page 94).  These lines, printed in Copies A, N-Q, read:
              
              The stern Bard ceas'd, asham'd of his own song; enrag'd he swung

              His harp aloft sounding, then dash'd its shining frame against

              A ruin'd pillar in glittring fragments; silent he turn'd away
              
              And wander'd down the vales of Kent in sick &amp; drear la-

              mentings.</note>
```

It's translating those additional spaces. So I fixed it for the note above. You can see my most recent commit. I was't sure if the lines needed an indent or not. But I tried using `&nbsp;` and that broke everything. So if the poem lines need any indentation, we'll need to figure out a different solution.

Clear as mud?

**Comment by foxm** [comment]
awesome
