### ISSUE TITLE
API

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#402]
do we need to do anything to make the API available?

**Comment by queryluke** [comment]
Nope try: http://london.lib.unc.edu/blake/api/copy/europe.k/objects

**Comment by foxm** [comment]
hmm, but query_works, etc. doesn't seem to be working

**Comment by queryluke** [comment]
look at the python scripts
`@api.route('/query_objects', methods=["POST"])`

`methods=["POST"]` means it only works via POST, not GET. I don't know why Nathan used POST for these. Changing it to GET isn't difficult, you'd need to remove the methods argument and then in main.js change any of the `return $http.post(url, config)` to `return $http.get(url)`. But you might want to check with him first.

**Comment by foxm** [comment]
ok, but what does query objects mean? i see /objects and /works, etc.

**Comment by foxm** [comment]
oh, it's a search. i see

**Comment by queryluke** [comment]
The query is a json object which includes a lot of other search parameters:
this is in /controllers/search/search.controller.js

The query string goes into the first attribute, but the entire object needs to be posted to the route.
```
$scope.searchConfig = {
            searchString: '',
            useCompDate: true,
            usePrintDate: false,
            searchAllFields: true,
            searchTitle: false,
            searchText: false,
            searchNotes: false,
            searchImageDescriptions: false,
            searchImageKeywords: false,
            searchWorks: false,
            searchCopies: false,
            searchAllTypes: true,
            searchIlluminatedBooks: false,
            searchCommercialBookIllustrations: false,
            searchSeparatePrints: false,
            searchDrawingsPaintings: false,
            searchManuscripts: false,
            searchRelatedMaterials: false,
            minDate: 1772,
            maxDate: 1827
        };
```

**Comment by foxm** [comment]
thanks
