### ISSUE TITLE
laocoon popout info boxes aren't showing title of work (Laocoon)

### ISSUE THREAD

**Issue by foxm** [blakearchive/archive#404]

**Comment by foxm** [comment]
@queryluke i'm getting the banner and the footer showing in the popout window now, and no info. it should be the other way around

**Comment by foxm** [comment]
@queryluke i mean, not the other way around. it should show a partial banner (no right-hand side buttons or search). and no footer. i think that's how it was

**Comment by foxm** [comment]
this is happening only for the Laocoon

**Comment by queryluke** [comment]
latest branch wasn't deployed
