### ISSUE TITLE
loading bar

### ISSUE THREAD

**Issue by queryluke** [blakearchive/archive#405]
@foxm I've added a loading bar branch for your review. It renders a gold bar across the top of the page, in hope to indicate to the use that the page is still loading (which is particularly slow for search and the reading view).

You mentioned in #319 you thought things would load faster when the javascript gets minified. I'm sorry to say that minifying the javascript saves about 300ms. I tried and deemed the increase too inconsequential to implement (because it would have taken significant development time to build in a js minifying workflow)

So until the overall code is refactored this is the speed you've got. Hopefully the loading bar will help. I've left it as a separate branch and will let you merge as you see fit

**Comment by foxm** [comment]
i like it very much. do you think the refactoring will make things significantly faster?

**Comment by queryluke** [comment]
It depends. There are quite a few reasons why the current code drags:

1. It's an older version of angular and older versions of other plugins
2. There are a LOT of conditionals peppered throughout to account for importing oddities and data inconsistencies. Specifically ng-if can be rather taxing.
3. Some of the templates are rather large and should be broken into smaller chunks
4. We've got a TON of digest cycles. Every ng-repeat, $scope.$on, and $watch, all require digest cycles.

A general code cleanup would help some but it will take a lot of time and testing to make sure updates don't break anything. RTI would be fairly low.

A complete front-end refactor (i.e., start a new repo and build a new app), you can focus solely on keeping speed a key factor. Just keep in mind that the more functionality you bake into a UI the slower it gets. It's a compromise.

**Comment by foxm** [comment]
Ok. Is the new version of Angular so much different that it would constitute a whole rewrite? Hope not.

**Comment by queryluke** [comment]
I think we're using 1.4...the newest version of angular1 is 1.5.something. that upgrade would not take a rewrite but you wouldn't see any noticeable performance increases.

If you choose a different platform, angular2, react, Vue, etc. It would require a complete rewrite.
