### ISSUE TITLE
link from homepage not opening up in object view

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#412]
@queryluke this happens occasionally and randomly. the previous image viewed shows. a timing thing?

**Comment by queryluke** [comment]
It's either 2 things:

1. The page isn't fully loaded. I've noticed that even though the page looks fully loaded, there is an additional image loading digest. So if you notice it again, wait maybe 5 seconds. I haven't seen one take 5 seconds, but just to be sure. If you wait 5 seconds and the old image is still showing then it might be:

2. The object image you've clicked on doesn't exist. Images in the homepage waterfall come from a different directory than images in the object viewer.
America a Prophecy, Copy A object 9:
On homepage: `http://www.blakearchive.org/blake/static/img/featured/america.a.p9.100.jpg`
In Object Viewer: `http://www.blakearchive.org/images/america.a.p9.100.jpg`

Open up the developers console and see if there was a 400 error. It would look something like this:
`Failed to load resource: the server responded with a status of 404 (NOT FOUND)` then on the right side of the console `http://www.blakearchive.org/blake/images/<image>`  where `<image>` is the image it failed to load. That means the image doesn't exist and needs to be put on the server. Or possibly there is a typo in the filename

**Comment by ba001** [comment]
@queryluke it's the letter object on the homepage that links to:

http://london.lib.unc.edu/blake/copy/ltapril1800.1?descId=lt1april1800.1.ltr.01

it should be **letters**?descId=lt1april1800.1.ltr.01

i changed home-page-images.csv, replacing the BAD column for this object with 'letters', but it didn't seem to change anything. i looked at the homepage import script as well as the homepage controller. it looks like they all check out. it should be picking up that change, but it's not. any ideas?
