### ISSUE TITLE
added twitter share button

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#425]
i've added a twitter share button ('twitter' branch), but i still need to figure out how to broadcast a change in the window location. right now, the button retains the original location when clicking on a new work or the next or previous object

**Comment by queryluke** [comment]
See https://docs.angularjs.org/api/ng/service/$location. Not `$window`. If you look at main.js line 990 & 991, you'll see where I'm setting the location. You'll need to set something in the controller or make a directive. You won't be able to simply replace `$window.location` with `$location.path`

Also, I've used this plugin before as well: https://720kb.github.io/angular-socialshare/, if you plan on sharing to other services in the future, it may be worth the effort to add now.

**Comment by ba001** [comment]
ok. i add the button in main.html, which doesn't have a controller, right? and wouldn't adding a directive in main.js amount to the same thing as using $location.path? sorry, i'm stumped on this one

**Comment by ba001** [comment]
see 'twitter' branch. i added a directive, but it still seems to retain the original path after the initial page load

**Comment by ba001** [comment]
fixed and deployed
