### ISSUE TITLE
s-los.f object 7

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#426]
@joeafletch joe, looks like there's an issue with s-los.f. object 7:

http://www.blakearchive.org/blake/copy/s-los.e?descId=s-los.e.illbk.07

go to Objects from Same Matrix.

i guess it should be changed to object 5 in the relations csv for each copy of s-los?

**Comment by joeafletch** [comment]
@ba001 That's right, Mike, it should be object 5 from copy F.

**Comment by ba001** [comment]
ok, had to fix a whole bunch of 'em--hope i go 'em all right
