### ISSUE TITLE
ordering of works in TOC

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#441]
works from the same year need to be ordered correctly.

in the BADs, compdate values with .X indicate ordering of works relative to others composed in the same year.

one solution to this is to manually add the .X's to the compdate strings in the works.csv file and then modify the import scripts to read the .X's to order the works accordingly

**Comment by nathan-rice** [comment]
The ordering should come from the database.  I can update the API to order according to an arbitrary model field.  I would be happy to always sort works by compdate_string - then you can tweak that string value to make the order come out exactly as you like it.

**Comment by ba001** [comment]
yes, that sounds good. let's wait till joe f. and i can confer on a paradigm
