### ISSUE TITLE
order biblical water colors by butlin number?

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#442]
http://www.blakearchive.org/work/biblicalwc

**Comment by nathan-rice** [comment]
Is the desired behavior to order objects by butlin numbers when available for all works?

**Comment by ba001** [comment]
no, the biblical water colors is apparently a special case. would it be possible to keep the ordering as it is for everything else but change the biblicalwc to be ordered by butlin number?

**Comment by ba001** [comment]
same with biblical tempera: biblicaltemperas

**Comment by nathan-rice** [comment]
I could certainly check if the work name is biblicalwatercolors/biblicaltemperas before telling the database how to sort.  That sort of special case behavior is generally a bad idea though - it would be better to come up with a single sort criterion that works in all cases.

**Comment by ba001** [comment]
Woops, to clarify, biblicalwc and biblicaltemperas must be sorted by butlin numbers. The other virtual groups, some of which also have butlin numbers, by the way, need to stay ordered as they are now

**Comment by ba001** [comment]
hold of on this. at the beginning of next semester, we're going to go through every virtual group to determine any other special cases

**Comment by ba001** [comment]
we've discussed virtual group orderings. all virtual groups except Letters should be ordered by Butlin number

**Comment by nathan-rice** [comment]
The easiest way to accomplish this is by sorting virtual groups besides letters by their desc_id.  Normally, this wouldn't work - because of how computers sort things, the ordering is not perfect, for example, 400.1 comes before 5.1.  However, I don't see any but documents below 100, so this should work for our case.

I've implemented and pushed this change.  Please test and let me know if anything further is required.

**Comment by ba001** [comment]
very nice, thanks. i'll deploy

**Comment by ba001** [comment]
uh oh, i just deployed and now i'm getting an internal server error

**Comment by ba001** [comment]
i reverted the commit thinking it might have been a problem with the commit, but apparently not. it seems to be caused by something else.

**Comment by ba001** [comment]
don't know what's going. now london works but not production. before the revert, the internal server error was occurring on both development and production

**Comment by ba001** [comment]
ok, both are working now, but i've reverted your commit. 

i see the problem from the logs. it's strange; your change worked fine when i tested it on my local setup, but when i deployed it, this error came up in the logs:

[Wed Jan 18 18:00:49 2017] [error] [client 66.249.64.110]   File "/htdocs/webdata/blakearchive/services.py", line 232
[Wed Jan 18 18:00:49 2017] [error] [client 66.249.64.110]      if bad_id in {"biblicalwc", "gravepd", "biblicaltemperas", "gravewc", "cpd", "gravewd", "pid"}:
[Wed Jan 18 18:00:49 2017] [error] [client 66.249.64.110]                                ^
[Wed Jan 18 18:00:49 2017] [error] [client 66.249.64.110]  SyntaxError: invalid syntax

maybe a python version issue?

**Comment by nathan-rice** [comment]
That is set literal notation, which is supported by python 2.7+.  If that wasn't working, it would indicate that you guys are operating using an **old** python (from about 8 years ago).  There are workarounds, but haven't we already been over this issue and established that python 2.7+ was the target?

**Comment by ba001** [comment]
@queryluke luke would be able to answer that better. The deploy uses a different version

**Comment by joeafletch** [comment]
We will eventually publish virtual groups containing Butlin numbers < 100 (but1.1.xml, for instance), so I'm not sure how this solution will work in those cases.

**Comment by ba001** [comment]
there's a python26 branch which gets merged in during the deploy. i don't think the Library ever let us use an updated python

**Comment by ba001** [comment]
i went ahead and converted that to python26 syntax, and @joeafletch, i added a field for butnumber to the Object model. it gets set with the butlin number from the desc id. so now when we publish vg's containing butlin numbers below 100, they'll get sorted properly
