### ISSUE TITLE
tooltip for i window

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#447]
@queryluke luke, how do you show a tooltip by default? i'm trying to place a tooltip to the right of the 'i' tab that shows up on load and disappears on click:

```
   Diplomatic Transcription 
 < Illustration Description    
   Editors' Notes     
```             
  
i've tried all kinds of things: different triggers, an init function, etc.

**Comment by queryluke** [comment]
Not sure what you mean "by default". There is an html "title" attribute. Which can be used like a tooltip. Like the modals, we're using v0.12.1 of angular UI. There is a [tooltip directive](http://angular-ui.github.io/bootstrap/versioned-docs/0.12.1/#/tooltip)

**Comment by ba001** [comment]
thanks. right now you have to hover your mouse over the 'i' button to see it. i wanted to have it display when the page loads, so that the user can know what's in the 'i' window, and then have it disappear when you click on the 'i' tab (open the 'i' window), and finally have it reappear when you close the 'i' window. if it's not possible to do all this with the built in functionality, it's ok as it is
