### ISSUE TITLE
Image Display in Editors' Notes

### ISSUE THREAD

**Issue by joeafletch** [blakearchive/archive#456]
There is an image that is indicated and meant to be displayed in the editors' notes for [BUT 404](http://www.blakearchive.org/copy/biblicaltemperas?descId=but404.1.pt.01). It was showing up on the [old site](https://web.archive.org/web/20160910072531/http://www.blakearchive.org/exist/blake/archive/editornotes.xq?objectid=but404.1.pt.01), but it's not getting displayed now, even though the image (but404.1.1.sg) is in the image repo. Is this a question of the new code not picking it up, or do we need to reformat the BAD in some way?

**Comment by ba001** [comment]
here's the relevant xml. note \<illus filename=...\>. does this need to be taken care of in the import stage or can the image be referenced using markdown syntax?

`<objnote><p>Blake signed the work with his monogram, lower right, and dated it; see the textual transcription.  An enhanced image of the monogram has been provided below.  The painting has been restored three times: between 1863 and 1880, between 1904 and 1907 (probably by Stanley William Littlejohn), and by John Hell c. 1950.</p><illus filename="but404.1.1.sg.300.jpg"/></objnote>`

**Comment by nathan-rice** [comment]
Only the textual contents of notes are imported currently - tags are stripped out.  We can alter this behavior, but there are a few issues:

* Those notes really shouldn't contain rendering markup if we can help it.  Paragraph is sort of semantic in this context, but I suspect that there are more egregious cases.  This should be examined.
* We need to figure out everything in the notes that should be extracted and stored, I'm sure this isn't the only corner case.
* The current interface won't accommodate stuffing a sizable image in to the editor's notes display - I'm going to tentatively suggest putting a small thumbnail with a link, and have that link open a full size image in a pop up.  The exact interface modification required is going to depend on what else you want me to extract and surface from the notes.

**Comment by ba001** [comment]
@queryluke luke, i got the images in the editors' notes working, but i'm getting some kind of GET image async error. go to:
http://london.lib.unc.edu/copy/biblicaltemperas
then, reload while the console is open and notice:

GET http://london.lib.unc.edu/images/%7B%7Bobject_note_image.filename%7D%7D

the images are showing in the editors' notes for the objects in this work (a lot of them have images in their notes), but that GET error is occurring. if you look at editorNotes.directive.js, you'll notice i added objectNoteImages(). is there something wrong with it that's causing that GET error? i'm stumped.

**Comment by ba001** [comment]
fixed. changed src to ng-src

**Comment by ba001** [comment]
whoops, still have to implement images for text notes. only did images for object notes.

**Comment by ba001** [comment]
done

**Comment by ericloy** [comment]
You guys rock.
