### ISSUE TITLE
search result preview not sizing properly

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#460]

**Comment by nathan-rice** [comment]
This should be fixed in the latest commit.

**Comment by ba001** [comment]
@nathan-rice great job on all the fixes. one more thing for this one. at the moment, when you close the preview the window scrolls all the way up. it should only scroll back up to the appropriate row. see production for how it should work.

**Comment by nathan-rice** [comment]
Should be fixed in the latest commit.

**Comment by ba001** [comment]
hmm, now it scrolls down (and quite a lot). see london.lib.unc.edu

**Comment by ba001** [comment]
it should just scroll up slightly so that the user can see the whole of the objects in that row

**Comment by nathan-rice** [comment]
Given that is not what I observed when I tested it myself, please include a specific step by step procedure for producing the error so I don't have to hunt around for an example.

**Comment by ba001** [comment]
1. go to london.lib.unc.edu in chrome
2. search 'angel'
3. click on the first result in the first row.
4. 'x' out of the preview
5. notice the whole thing scrolls down

**Comment by nathan-rice** [comment]
Turns out this behavior was the result of angular shuffling the DOM around, and the inconsistent behavior was the result of some results being cached by the browser, and thus the scroll-to-element directive loading before angular applied the hidden style to all of the preview boxes.  Very easy to fix though.  Have a look at the latest commit, should be solved.

**Comment by ba001** [comment]
still some issues, unfortunately:

if you click on the first result in the first row, then close the preview, the window will scroll up but not quite far enough. the whole of the images should show

and if you then click on the first result of the second row, then close the preview, the window will scroll down

**Comment by ba001** [comment]
fixed
