### ISSUE TITLE
magnify not working

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#462]

**Comment by nathan-rice** [comment]
I don't have any of the images on my development system so I can't test this.  Please make the images easily available for download.

**Comment by ba001** [comment]
do you have the wren key? the images are at london.lib.unc.edu:/htdocs/blake_assets/images. you can rsync them with the user wren.

@queryluke can we give nathan the wren key, if he doesn't have it already?

**Comment by queryluke** [comment]
as long as you pass to him via a secure channel. but I thought nathan had ssh access to london (via onyen)

**Comment by nathan-rice** [comment]
Nope.

**Comment by ba001** [comment]
@queryluke i don't know of a secure way to pass him the key. would you mind doing that?

**Comment by queryluke** [comment]
I've put in a ticket with our sysadmins to give nathan ssh access to london. They said they'll get it done this afternoon.

**Comment by queryluke** [comment]
ok, @nathan-rice your should have ssh access to london. If you're off-campus, you'll need to use a vpn

**Comment by nathan-rice** [comment]
This should be fixed in the latest commit.
