### ISSUE TITLE
search preview window doesn't reset when searching again (something else)

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#463]

**Comment by nathan-rice** [comment]
I am not observing this behavior.  I tried a search with the term "angel", opened the preview window and then searched for the term "demon" and the preview window disappeared.  Please provide more specific information so I can reproduce this.

**Comment by ba001** [comment]
i just tried that and got the same problem. by preview window i mean the window that comes up when you click once on a handprint. i'm using chrome.

**Comment by nathan-rice** [comment]
I was finally able to reproduce this.  Not sure why it only happens sometimes, but it was easy to fix.  See the latest commit.

**Comment by ba001** [comment]
nice
