### ISSUE TITLE
the 'Medium' search filter isn't working

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#488]
@nathan-rice 
search 'angel', select "Illuminated Books", notice everything disappears. there are several illuminated books with 'angel'

also, notice that when selecting "Illuminated Books" and then selecting "Any", "Illuminated Books" remains checked

**Comment by ba001** [comment]
@nathan-rice this might have cropped up after you implemented the resetResults. if that's the problem, you can take out that functionality

**Comment by nathan-rice** [comment]
This is actually a consequence of clearing the search box contents, not of resetting the results.  I reverted that behavior.

**Comment by ba001** [comment]
@nathan-rice ok, almost. selecting "Any" after checking another one still doesn't execute. also, if you don't mind, you can branch off the latest master. i've been having to resolve conflicts

**Comment by ba001** [comment]
fixed. there was a typo
