### ISSUE TITLE
object title is being populated by supplemental object title

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#494]
@nathan-rice 

in this example:

http://london.lib.unc.edu/copy/s-los.f?descId=s-los.f.illbk.05

this object has no title in the BAD, but the object title that shows is 'Full Leaf View', which is the title for the supplemental object. for the original view, there should be no title showing. 

when the original object has a title, as in this example:

http://london.lib.unc.edu/copy/america.b?descId=america.b.illbk.02

the title shows correctly.

is the import.py picking up a supplemental title for the original object title?

**Comment by ba001** [comment]
fixed

**Comment by ba001** [comment]
@joeafletch joe, for supplemental objects, maybe we should put the object number in with the view description, so for s-los.f, for example, i added 'Object 5' before 'Full Leaf View'. this way, the label for the supp view object when you're viewing it tells you what object number you're on.

` <supplemental>
                <desc dbi="s-los.F.P5-full" id="supps-los.f.rm.01">
                    <objtitle>, 
                        <objid>
                            <objnumber code="A1">Object 5 Full Leaf View</objnumber></objid>
                    </objtitle>
                    <physdesc desclevel="brief">
                        <objsize>37.1 x 26.0 cm.</objsize>
                        <windowsize height="1206" width="910"/>
                    </physdesc>
                </desc>
            </supplemental>`

**Comment by joeafletch** [comment]
@ba001 That makes good sense to me, but we'll have to go back through the BADs and add that--shouldn't take too long.
