### ISSUE TITLE
virtual group objects in objects_from_same are not numbered correctly

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#495]
@nathan-rice 

for example:

http://london.lib.unc.edu/copy/but544.1?descId=but544.1.wc.07

click on Objects From the Same Production Sequence.

notice that the virtual group object shown under that tab is labeled Object 1. it is actually Object 13 in the virtual group. if you click on it, you'll see it labeled in the gallery as Object 1, but if you click next object and then previous object to get back to it, it'll be labeled correctly. i see that virtual group objects are numbered as virtual groups are loaded in the object view (numberVirtualWorkObjects()). but they'll have to be numbered before so that they're labeled correctly under objects_from_same tabs.

**Comment by nathan-rice** [comment]
This is easily addressed by using the object_number rather than full_object_id for virtual works.  I should note that that object is actually object 16, but the numberVirtualWorkObjects skips supplemental objects.

**Comment by ba001** [comment]
hmm, your second comment confused me. are you saying Object 16 will display when using object_number? that wouldn't be correct. will test it sometime this week.

**Comment by nathan-rice** [comment]
Yes, when I tested using object number instead of full_object_id, 16 was displayed.

**Comment by ba001** [comment]
ok, we'll have to come up with another solution then

**Comment by nathan-rice** [comment]
Given the fact that we have a field that almost does what we want, and the problem is being caused by supplemental objects being incorrectly treated as regular objects, the simplest thing to do would be to handle supplemental objects differently.  I'm happy to examine solutions in that direction.  Having randomly firing javascript that renumbers objects, not so much.

**Comment by ba001** [comment]
could we just re-assign the object_number field in numberVirtualWorkObjects as supplemental objects are skipped? i'm reluctant to change the way we handle supplemental objects in the back end because at this point it's so tightly couple with much of the javascript and not only where we actually display supplemental objects

**Comment by ba001** [comment]
on the other hand, if you think you could easily modify the javascript with a change to the supplemental objects, then yes, let's go that route. will look into it more closely soon

**Comment by ba001** [comment]
fixed with fdc0ddf17fe26a627d392753f5034d1cc60778f1
