### ISSUE TITLE
sorting virtual objects by order they are in in works.csv

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#507]
@nathan-rice 

if we were to sort virtual objects in a virtual work by the order they are in in works.csv, how would we do this? i tried removing the order_by line in the following, but i got inconsistent results; the order displayed didn't match up with the order in works.csv:

 ```
@staticmethod
    def get_virtual_sorted_query():
        query = models.BlakeObject.query \
            .order_by(models.BlakeObject.butnumber) \
            .filter(models.BlakeObject.supplemental == None)
        return query
```

**Comment by nathan-rice** [comment]
It looks like the object_number would work as a new sorting criterion, would it not?  Looking at the code, the object_number should correspond to the position in the bad_id field for virtual works.

**Comment by ba001** [comment]
@nathan-rice hmm, i'm not sure. we want the order of the entries under the column virtual_objects in works.csv to be the order displayed

**Comment by ba001** [comment]
that way we can manually sort objects in a virtual work

**Comment by nathan-rice** [comment]
If you look at the import.py script, note that object_number is determined by the order of the objects collection - see [here](https://github.com/blakearchive/archive/blob/master/blakearchive/import.py#L201).  That objects collection's order is determined by the order of appearance in the virtual_objects field - see [here](https://github.com/blakearchive/archive/blob/master/blakearchive/import.py#L183).  Thus object_number *should* do what you want.  If it doesn't, you might need to tweak the objects_sorted_for_virtual_copy function slightly to make sure it maintains its input order.

**Comment by ba001** [comment]
object_number did the trick, thanks. so i guess object_number doesn't correspond to the object number displayed (Object 1, Object 2, etc. on the work info page)
