### ISSUE TITLE
get more images on homepage

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#516]
@queryluke luke, is there a simple way to get the homepage to display more columns, 10 instead of 6, of images? i was able to add columns, but they weren't being filled up with images. i tried adjusting some numbers in home.controller.js. i can't figure out how the columns are being populated with images. i thought at first the problem might be that we don't have enough featured images to fill up 10 columns, so i tried allowing duplicates but that didn't seem to work either. i'm stumped. if there's an easy way to do this, let me know. otherwise, don't worry about it. it's not a pressing issue.

**Comment by queryluke** [comment]
In the home controller, starting on [line 36](https://github.com/blakearchive/archive/blob/master/blakearchive/static/controllers/home/home.controller.js#L36), the code is looping through the images and adding a "column" attribute to each image. It increments the [column number every 4 images](https://github.com/blakearchive/archive/blob/master/blakearchive/static/controllers/home/home.controller.js#L45). Thus, each column only contain 4 images.

You can increase this number, but you'll also need to add more images to [home-page-images.csv](https://github.com/blakearchive/data/blob/master/csv/home-page-images.csv). Right now, you've got 41 images.

**Comment by ba001** [comment]
@queryluke Yeah, I tried that. If I increase the 3, I get fewer columns. In home.html I changed col-sm-2 to col-sm-1 and decreased that 3 in the home controller to 1, and that gives me 12 columns but some of them are unfilled. If I increase the 3 to say 6, I get 4 filled columns and the rest is empty space.

**Comment by queryluke** [comment]
Are you adding column objects at the top of the controller?
https://github.com/blakearchive/archive/blob/master/blakearchive/static/controllers/home/home.controller.js#L12

**Comment by ba001** [comment]
yeah, adding to 12. i'm gonna revert the change

**Comment by queryluke** [comment]
ok, then it sounds like you don't have enough images to fill 12 columns. You'll need to add more to [home-page-images.csv](https://github.com/blakearchive/data/blob/master/csv/home-page-images.csv).
