### ISSUE TITLE
what the flying *!&# is going on with the work page of but543 showing the wrong title

### ISSUE THREAD

**Issue by ba001** [blakearchive/archive#529]
http://london.lib.unc.edu/work/but543

it should read: Illustrations to Milton's 'L'Allegro' and 'Il Penseroso'

@jbartonthomas jewell, you might be able to help me with this one. we can talk about it when we see  each other again

**Comment by ba001** [comment]
fixed

**Comment by joeafletch** [comment]
Thanks, Mike, and phew! Hope you weren't banging away at it for hours this evening.

**Comment by jbartonthomas** [comment]
Hi Guys,

I'm sorry that I missed this. I was out of town last week.

Jewell
