### ISSUE TITLE
Virtual Groups - missing image

### ISSUE THREAD

**Issue by queryluke** [blakearchive/archive#54]
The cover image/handprint on the work page is missing; the image dbi file is indicated in column D on works.csv

the image that is returned from the database is "but146.1.wc.01", but that doesn't point to anything 
http://www.blakearchive.org/blake/images/but146.1.wc.01.100.jpg

That's the desc id for the object, but the image is titled according to the dbi (both desc id and dbi information for all objects in the Archive are listed in the first two columns of the relational table), which is slightly different: BUT146.1.1.WC.100.jpg. I can't tell if it's a database issue, but the problem does just seem to be restricted to virtual groups.

**Comment by roastduckalamode** [comment]
@foxm @joeafletch 

This is an issue with the works.csv file. 

If you look at the "cover image" column of  "Illustrations to the Bible"  (water color), row 6. The "cover image" is **but146.1.wc.01**. But, as I understand it, it should be the first image for the first object in this virtual group. To fix this, you'll need to change the cover image column for the virtual groups. In this instance it would be **but146.1.1.wc**, and then we'll need to re-import the works file.

However, there was discussion on 2/15, about additional options for the works view of a virtual group. We can hold off on fixing this until you all have decided how you want the works page for virtual groups to look.

**Comment by roastduckalamode** [comment]
@foxm See my second comment. When the repo's works.csv is updated and we reseed the database, this should be resolved. Just notify me here when the works.csv is updated.

**Comment by joeafletch** [comment]
@queryluke Jumping back in here to suggest something that Mike and I discussed regarding this issue. We've acknowledged (with Joe V.) that it's impossible to treat virtual groups as exactly the same as other works, for various reasons. That's why on the work page for such groups we want to display all the objects in the group in the grid below the textual description. Since members of virtual groups are all separate works, we're hesitant to assign a single image to represent them. So we'd like to try to represent virtual groups in search results, etc. using just text. Instead of an image handprint and accompanying title, the icon would be a handprint-sized title: "Water Color Illustrations to the Bible" for example (broken into however many lines are necessary to fit inside the handprint rectangle. Users could then click on that and go to the work page, as usual.

**Comment by queryluke** [comment]
@joeafletch @foxm 

I've pushed an update. This turned out to be 2 problems. I've fixed the first: the virtual works pages will show all objects. 

However there is still a discrepancy for search results. The object/copy search results are displayed in a way that the representative image is the first matching object within a work. For example, search for "angel". Notice the difference in the representative images for **Songs of Innocence** under the **Title** and **Transcription** results. Title uses **Copy A, Object 35**. Transcription uses **Copy A, Object 8**. For copy results, the first object of a matching copy is displayed.

Therefore, this issue isn't limited to virtual works but ALL works. I.e., no work has a single representative image.

So you've got some options.

* Option 1: Display only text for all work results
  * how the search is set up now
* Option 2: Display the first object of the first copy (for regular works) and text for virtual works.
  * This appears to be functionality you're requesting in your comment above.
* Option 3: Display the first possible representative object
  * this would be the first object in a virtual group. Or the first object in the first copy of a regular work.

If you choose Option 2 or 3, you'll still need to assign a representative image in the works.csv file. Though it is possible to programmatically query the first object in the first copy, it would be much faster and require less processing if the representative image were listed in the csv. It would also empower future editors to edit the values in the csv, changing the representative image on the site.

Finally, I'll throw in my 2 cents...seeing the text titles looks like an error or unfinished produced. I understand the conceptual hesitation to represent a virtual work with a single image, but its a very nuanced difference that most users would overlook. Thus, my vote is for option 3 but ultimately your decision.

**Comment by foxm** [comment]
@queryluke @joeafletch luke, good point, regarding text titles looking like errors. just thought of something. how about a handprint that depicts a cluster of objects (objects in a virtual group or first objects of copies in a work), as in this photo of album covers: https://albumcoverhalloffame.files.wordpress.com/2013/03/briefhistac1.jpg

**Comment by queryluke** [comment]
need to reseed database to get works images
