### ISSUE TITLE
Virtual groups - related items spacing

### ISSUE THREAD

**Issue by queryluke** [blakearchive/archive#57]
There’s some weird spacing in the “All Known Related Items” list. Any idea why the items aren’t displaying exactly as they do on the current site?

**Comment by roastduckalamode** [comment]
The "related_works" query returns 2 sets of data, "title" and "info". The "info" string has html in it, specifically "<br>". The rendering script outputs the title, then the info. So this weird spacing is in the info string. Not sure how to proceed, but sounds like it needs to be fixed on the data end.

**Comment by queryluke** [comment]
dup of #200
