### ISSUE TITLE
import script warnings

### ISSUE THREAD

**Issue by roastduckalamode** [blakearchive/archive#92]
I spun up a local solr install and postgres db so I can experiement with making our cap files. Here are some warnings and errors I get.

@nathan-rice if you could look these over. I just want to confirm you're seeing the same thing when you import.

## import.py ##
happens 10 times then is suppressed. This is the first of the 10. 
```
blake/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value '<p>The Bible had an enorm...'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
```

## homepage.py ##
essentially the same thing
```
/blake/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'america.a.p9'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
```

## solrimport.py ##
After I import, I get 20 blake-object documents but my blake-works documents are 0. Additionally, I'm using solr 5.4.0. Should I switch to 5.4.1?
```
Traceback (most recent call last):
  File "solrimport.py", line 67, in <module>
    main()
  File "solrimport.py", line 50, in main
    blake_object_solr.add([obj])
  File "/Users/lukeluke/Sites/blake/lib/python2.7/site-packages/pysolr.py", line 813, in add
    return self._update(m, commit=commit, softCommit=softCommit, waitFlush=waitFlush, waitSearcher=waitSearcher)
  File "/Users/lukeluke/Sites/blake/lib/python2.7/site-packages/pysolr.py", line 399, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/Users/lukeluke/Sites/blake/lib/python2.7/site-packages/pysolr.py", line 331, in _send_request
    raise SolrError(error_message)
pysolr.SolrError: [Reason: Exception writing document id 20 to the index; possible analysis error.]
```

**Comment by nathan-rice** [comment]
The unicode warning is a non issue, it is a result of non-unicode python strings being supplied for a unicode database field.  This is only something we need to fix if the source data for the field contains unicode characters, which end up appearing on the site incorrectly.

As for the error you're running into with solrimport.py, that is a configuration error on your part, I can't really debug it remotely.   As a test I installed and configured a local copy of solr 5.5, and I was able to load all the documents into the index without issue.  If it is helpful I can write up some sort instructions on how to properly create a core and update the solrconfig.xml/schema.xml.

**Comment by roastduckalamode** [comment]
I'll try solr 5.5 first and if I'm still having issues, I'll ask for a copy of your solrconfig.xml

**Comment by roastduckalamode** [comment]
@nathan-rice I'm still getting this error in 5.5, but I get a more descriptive error message:

Did you set something in your config file to get around this? Maybe it would help if you sent me your solrconfig.xml file and I can look into how it differs.
```
raise SolrError(error_message)
pysolr.SolrError: [Reason: Exception writing document id 20 to the index; possible analysis error: Document contains at least one immense term in field="components" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[91, 123, 34, 99, 111, 109, 112, 111, 110, 101, 110, 116, 34, 58, 32, 123, 34, 99, 104, 97, 114, 97, 99, 116, 101, 114, 105, 115, 116, 105]...', original message: bytes can be at most 32766 in length; got 49613. Perhaps the document has an indexed string field (solr.StrField) which is too large]
```

**Comment by nathan-rice** [comment]
See attached.

[solr.xml.zip](https://github.com/blakearchive/archive/files/155719/solr.xml.zip)

[blake-work.schema.xml.zip](https://github.com/blakearchive/archive/files/155725/blake-work.schema.xml.zip)
[blake-object.schema.xml.zip](https://github.com/blakearchive/archive/files/155733/blake-object.schema.xml.zip)
