### ISSUE TITLE
Extra space in tei content

### ISSUE THREAD

**Issue by roastduckalamode** [blakearchive/archive#98]
@nathan-rice 

http://localhost:8002/blake/copy/mhh.b?objectId=350 here is a simple example.

If you look at the textual transcription div in dev tools, you'll have to open a lot of nested elements, but if you get to a <td class="tei-line-text">, the &nbsp; have line breaks or addition spacing.

I can also keep looking into a css solution if you can't find an easy one on your end.

**Comment by roastduckalamode** [comment]
You'll need to switch to the reading view banch to see the tei content.

**Comment by nathan-rice** [comment]
Fixed.
